Repository acts-project/detray, pull requests merged in 2021-11, with the labels that each got.

#158 remove auto from `grid2` template parameter
  core/include/detray/grids/grid2.hpp
  core/include/detray/grids/populator.hpp
  tests/unit_tests/core/grids_grid2.cpp
  tests/unit_tests/core/grids_populator.cpp
  tests/unit_tests/cuda/grids_grid2_cuda_kernel.hpp
Labels: bug

#157 feat: run random direction navigation on toy geometry
  core/include/detray/tools/single_type_navigator.hpp
  tests/common/include/tests/common/check_geometry_navigation.inl
  tests/common/include/tests/common/tools_single_type_navigator.inl
Labels: enhancement

#162 Change detray_qualifiers.hpp to qualifiers.hpp
  core/CMakeLists.txt
  core/include/detray/core/mask_store.hpp
  core/include/detray/core/transform_store.hpp
  core/include/detray/definitions/detail/accessor.hpp
  core/include/detray/definitions/invalid_values.hpp
  core/include/detray/definitions/qualifiers.hpp
  core/include/detray/geometry/index_geometry.hpp
  core/include/detray/geometry/object_registry.hpp
  core/include/detray/geometry/unified_index_geometry.hpp
  core/include/detray/geometry/volume.hpp
  core/include/detray/grids/axis.hpp
  core/include/detray/grids/grid2.hpp
  core/include/detray/grids/populator.hpp
  core/include/detray/grids/serializer2.hpp
  core/include/detray/masks/annulus2.hpp
  core/include/detray/masks/cylinder3.hpp
  core/include/detray/masks/rectangle2.hpp
  core/include/detray/masks/ring2.hpp
  core/include/detray/masks/single3.hpp
  core/include/detray/masks/trapezoid2.hpp
  core/include/detray/tools/toy_geometry.hpp
  core/include/detray/utils/enumerate.hpp
  tests/common/include/tests/common/test_defs.hpp
  tests/unit_tests/cuda/tuple_test_cuda_kernel.hpp
Labels: naming

#163 Refactor `mask_store_data`
  core/include/detray/core/mask_store.hpp
  tests/unit_tests/cuda/mask_store_cuda_kernel.cu
  tests/unit_tests/cuda/mask_store_cuda_kernel.hpp
  tests/unit_tests/cuda/tuple_test_cuda_kernel.cu
  tests/unit_tests/cuda/tuple_test_cuda_kernel.hpp
Labels: refactor

#161 Rewrite toy detector with `detector` and `unified_index_geometry`
  core/include/detray/core/detector.hpp
  core/include/detray/geometry/object_registry.hpp
  core/include/detray/geometry/unified_index_geometry.hpp
  core/include/detray/grids/grid2.hpp
  core/include/detray/tools/intersection_kernel.hpp
  core/include/detray/tools/single_type_navigator.hpp
  core/include/detray/tools/toy_geometry.hpp
  tests/common/include/tests/common/check_geometry_linking.inl
  tests/common/include/tests/common/check_geometry_navigation.inl
  tests/common/include/tests/common/check_geometry_scan.inl
  tests/common/include/tests/common/test_toy_geometry.inl
  tests/common/include/tests/common/tools/create_toy_geometry.hpp
  tests/common/include/tests/common/tools/ray_gun.hpp
  tests/common/include/tests/common/tools_single_type_navigator.inl
Labels: refactor

#164 ref: merge geometry with detector
  apps/common/include/apps/common/display_bin_association.inl
  apps/common/include/apps/common/display_layers.inl
  core/include/detray/core/detector.hpp
  core/include/detray/geometry/index_geometry.hpp
  core/include/detray/geometry/object_registry.hpp
  core/include/detray/geometry/unified_index_geometry.hpp
  core/include/detray/geometry/volume.hpp
  core/include/detray/geometry/volume_connector.hpp
  core/include/detray/tools/geometry_graph.hpp
  core/include/detray/tools/navigator.hpp
  core/include/detray/tools/propagator.hpp
  core/include/detray/tools/single_type_navigator.hpp
  io/csv/include/detray/io/csv_io.hpp
  tests/common/include/tests/common/benchmark_intersect_all.inl
  tests/common/include/tests/common/check_geometry_linking.inl
  tests/common/include/tests/common/check_geometry_navigation.inl
  tests/common/include/tests/common/check_geometry_scan.inl
  tests/common/include/tests/common/core_detector.inl
  tests/common/include/tests/common/geometry_graph.inl
  tests/common/include/tests/common/geometry_index_geometry.inl
  tests/common/include/tests/common/geometry_unified_index_geometry.inl
  tests/common/include/tests/common/masks_containers.inl
  tests/common/include/tests/common/test_toy_geometry.inl
  tests/common/include/tests/common/tools/create_toy_geometry.hpp
  tests/common/include/tests/common/tools/ray_gun.hpp
  tests/common/include/tests/common/tools_navigator.inl
  tests/common/include/tests/common/tools_propagator.inl
  tests/common/include/tests/common/tools_single_type_navigator.inl
  tests/unit_tests/CMakeLists.txt
  tests/unit_tests/array/array_index_geometry.cpp
  tests/unit_tests/array/array_masks_container.cpp
  tests/unit_tests/array/array_single_type_navigator.cpp
  tests/unit_tests/array/array_unified_index_geometry.cpp
  tests/unit_tests/cuda/CMakeLists.txt
  tests/unit_tests/cuda/index_geometry_cuda.cpp
  tests/unit_tests/cuda/index_geometry_cuda_kernel.cu
  tests/unit_tests/cuda/index_geometry_cuda_kernel.hpp
  tests/unit_tests/cuda/unified_index_geometry_cuda.cpp
  tests/unit_tests/cuda/unified_index_geometry_cuda_kernel.cu
  tests/unit_tests/cuda/unified_index_geometry_cuda_kernel.hpp
  tests/unit_tests/eigen/eigen_index_geometry.cpp
  tests/unit_tests/eigen/eigen_masks_container.cpp
  tests/unit_tests/eigen/eigen_single_type_navigator.cpp
  tests/unit_tests/eigen/eigen_unified_index_geometry.cpp
  tests/unit_tests/smatrix/smatrix_index_geometry.cpp
  tests/unit_tests/smatrix/smatrix_masks_container.cpp
  tests/unit_tests/smatrix/smatrix_single_type_navigator.cpp
  tests/unit_tests/smatrix/smatrix_unified_index_geometry.cpp
  tests/unit_tests/vc/vc_array_index_geometry.cpp
  tests/unit_tests/vc/vc_array_masks_container.cpp
  tests/unit_tests/vc/vc_array_single_type_navigator.cpp
  tests/unit_tests/vc/vc_array_unified_index_geometry.cpp
Labels: refactor

#166 Iterator Range Simplification, main branch (2021.11.26.)
  core/include/detray/utils/enumerate.hpp
Labels: bug
