Repository acts-project/detray, pull requests merged in 2022-10, with the labels that each got.

#283 feat: Add surface finder container to detector
  core/CMakeLists.txt
  core/include/detray/core/detail/tuple_array_container.hpp
  core/include/detray/core/detail/tuple_container.hpp
  core/include/detray/core/detail/tuple_vector_container.hpp
  core/include/detray/core/detector.hpp
  core/include/detray/core/detector_kernel.hpp
  core/include/detray/core/type_registry.hpp
  core/include/detray/definitions/indexing.hpp
  core/include/detray/geometry/surface.hpp
  core/include/detray/geometry/volume.hpp
  core/include/detray/geometry/volume_connector.hpp
  core/include/detray/geometry/volume_graph.hpp
  core/include/detray/grids/grid2.hpp
  core/include/detray/intersection/intersection_kernel.hpp
  core/include/detray/masks/annulus2.hpp
  core/include/detray/masks/mask_base.hpp
  core/include/detray/propagator/navigator.hpp
  core/include/detray/surface_finders/brute_force_finder.hpp
  core/include/detray/surface_finders/grid2_finder.hpp
  core/include/detray/surface_finders/neighborhood_kernel.hpp
  core/include/detray/tools/bin_association.hpp
  core/include/detray/tools/generators.hpp
  core/include/detray/utils/enumerate.hpp
  io/csv/include/detray/io/csv_io.hpp
  tests/benchmarks/cuda/benchmark_propagator_cuda.cpp
  tests/common/include/tests/common/benchmark_find_volume.inl
  tests/common/include/tests/common/benchmark_intersect_all.inl
  tests/common/include/tests/common/core_container.inl
  tests/common/include/tests/common/core_detector.inl
  tests/common/include/tests/common/geometry_volume.inl
  tests/common/include/tests/common/test_toy_geometry.inl
  tests/common/include/tests/common/tools/create_telescope_detector.hpp
  tests/common/include/tests/common/tools/create_toy_geometry.hpp
  tests/common/include/tests/common/tools/detector_metadata.hpp
  tests/common/include/tests/common/tools/intersectors/helix_intersection_kernel.hpp
  tests/common/include/tests/common/tools/particle_gun.hpp
  tests/common/include/tests/common/tools_intersection_kernel.inl
  tests/unit_tests/cuda/detector_cuda_kernel.cu
  tests/unit_tests/cuda/navigator_cuda.cpp
Labels: enhancement

#311 Replace constant magnetic field with covfie fields
  CMakeLists.txt
  core/CMakeLists.txt
  core/include/detray/core/detector.hpp
  core/include/detray/field/constant_magnetic_field.hpp
  core/include/detray/propagator/rk_stepper.hpp
  core/include/detray/propagator/rk_stepper.ipp
  extern/covfie/CMakeLists.txt
  io/csv/include/detray/io/csv_io.hpp
  tests/benchmarks/cuda/benchmark_propagator_cuda.cpp
  tests/benchmarks/cuda/benchmark_propagator_cuda_kernel.cu
  tests/benchmarks/cuda/benchmark_propagator_cuda_kernel.hpp
  tests/common/CMakeLists.txt
  tests/common/include/tests/common/check_geometry_navigation.inl
  tests/common/include/tests/common/core_detector.inl
  tests/common/include/tests/common/test_telescope_detector.inl
  tests/common/include/tests/common/tools/create_telescope_detector.hpp
  tests/common/include/tests/common/tools/create_toy_geometry.hpp
  tests/common/include/tests/common/tools/detector_metadata.hpp
  tests/common/include/tests/common/tools_guided_navigator.inl
  tests/common/include/tests/common/tools_propagator.inl
  tests/common/include/tests/common/tools_stepper.inl
  tests/unit_tests/covfie/CMakeLists.txt
  tests/unit_tests/covfie/constant_field.cpp
  tests/unit_tests/cuda/detector_cuda_kernel.hpp
  tests/unit_tests/cuda/navigator_cuda_kernel.hpp
  tests/unit_tests/cuda/propagator_cuda.cpp
  tests/unit_tests/cuda/propagator_cuda_kernel.cu
  tests/unit_tests/cuda/propagator_cuda_kernel.hpp
  tests/unit_tests/cuda/rk_stepper_cuda.cpp
  tests/unit_tests/cuda/rk_stepper_cuda_kernel.cu
  tests/unit_tests/cuda/rk_stepper_cuda_kernel.hpp
Labels: refactor

#303 feat: detray ranges
  core/CMakeLists.txt
  core/include/detray/core/detail/tuple_container.hpp
  core/include/detray/core/detector.hpp
  core/include/detray/core/transform_store.hpp
  core/include/detray/definitions/detail/accessor.hpp
  core/include/detray/definitions/units.hpp
  core/include/detray/geometry/volume_graph.hpp
  core/include/detray/intersection/intersection_kernel.hpp
  core/include/detray/propagator/actor_chain.hpp
  core/include/detray/propagator/base_actor.hpp
  core/include/detray/propagator/navigator.hpp
  core/include/detray/surface_finders/grid/detail/populator_impl.hpp
  core/include/detray/tools/bin_association.hpp
  core/include/detray/utils/enumerate.hpp
  core/include/detray/utils/ranges.hpp
  core/include/detray/utils/ranges/detail/iterator_functions.hpp
  core/include/detray/utils/ranges/empty.hpp
  core/include/detray/utils/ranges/enumerate.hpp
  core/include/detray/utils/ranges/iota.hpp
  core/include/detray/utils/ranges/join.hpp
  core/include/detray/utils/ranges/pick.hpp
  core/include/detray/utils/ranges/ranges.hpp
  core/include/detray/utils/ranges/single.hpp
  core/include/detray/utils/ranges/subrange.hpp
  core/include/detray/utils/type_traits.hpp
  io/csv/include/detray/io/csv_io.hpp
  tests/common/include/tests/common/benchmark_intersect_all.inl
  tests/common/include/tests/common/check_geometry_linking.inl
  tests/common/include/tests/common/check_geometry_navigation.inl
  tests/common/include/tests/common/geometry_volume_graph.inl
  tests/common/include/tests/common/grid_grid.inl
  tests/common/include/tests/common/grid_populator.inl
  tests/common/include/tests/common/tools/hash_tree.hpp
  tests/common/include/tests/common/tools/intersectors/helix_intersection_kernel.hpp
  tests/common/include/tests/common/tools/particle_gun.hpp
  tests/common/include/tests/common/tools/ray_scan_utils.hpp
  tests/common/include/tests/common/tools/test_surfaces.hpp
  tests/common/include/tests/common/tools/track_generators.hpp
  tests/common/include/tests/common/tools_intersection_kernel.inl
  tests/common/include/tests/common/tools_track_generators.inl
  tests/unit_tests/core/CMakeLists.txt
  tests/unit_tests/core/utils_enumerate.cpp
  tests/unit_tests/core/utils_local_object_finder.cpp
  tests/unit_tests/core/utils_ranges.cpp
  tests/unit_tests/cuda/CMakeLists.txt
  tests/unit_tests/cuda/detector_cuda.cpp
  tests/unit_tests/cuda/detector_cuda_kernel.cu
  tests/unit_tests/cuda/detector_cuda_kernel.hpp
  tests/unit_tests/cuda/sf_finders_grid_cuda.cpp
  tests/unit_tests/cuda/utils_enumerate_cuda.cpp
  tests/unit_tests/cuda/utils_enumerate_cuda_kernel.cu
  tests/unit_tests/cuda/utils_enumerate_cuda_kernel.hpp
  tests/unit_tests/cuda/utils_ranges_cuda.cpp
  tests/unit_tests/cuda/utils_ranges_cuda_kernel.cu
  tests/unit_tests/cuda/utils_ranges_cuda_kernel.hpp
Labels: enhancement, refactor
