Repository acts-project/detray, pull requests merged in 2022-02, with the labels that each got.

#200 feat: Introduce detector metadata
  core/include/detray/core/detector.hpp
  core/include/detray/core/mask_store.hpp
  core/include/detray/core/surfaces_finder.hpp
  core/include/detray/core/transform_store.hpp
  core/include/detray/core/type_registry.hpp
  core/include/detray/geometry/object_registry.hpp
  core/include/detray/geometry/surface_base.hpp
  core/include/detray/geometry/volume.hpp
  core/include/detray/geometry/volume_connector.hpp
  core/include/detray/grids/axis.hpp
  core/include/detray/grids/grid2.hpp
  core/include/detray/grids/populator.hpp
  core/include/detray/grids/serializer2.hpp
  core/include/detray/masks/annulus2.hpp
  core/include/detray/masks/cylinder3.hpp
  core/include/detray/masks/mask_identifier.hpp
  core/include/detray/masks/rectangle2.hpp
  core/include/detray/masks/ring2.hpp
  core/include/detray/masks/single3.hpp
  core/include/detray/masks/trapezoid2.hpp
  core/include/detray/masks/unmasked.hpp
  core/include/detray/tools/bin_association.hpp
  core/include/detray/tools/concentric_cylinder_intersector.hpp
  core/include/detray/tools/geometry_graph.hpp
  core/include/detray/tools/grid_array_helper.hpp
  core/include/detray/tools/local_object_finder.hpp
  core/include/detray/tools/navigator.hpp
  core/include/detray/utils/c_step.hpp
  core/include/detray/utils/containers.hpp
  core/include/detray/utils/generators.hpp
  core/include/detray/utils/quadratic_equation.hpp
  io/csv/include/detray/io/csv_io.hpp
  plugins/algebra/array/include/detray/plugins/algebra/array_definitions.hpp
  plugins/algebra/eigen/include/detray/plugins/algebra/eigen_definitions.hpp
  plugins/algebra/smatrix/include/detray/plugins/algebra/smatrix_definitions.hpp
  plugins/algebra/vc/include/detray/plugins/algebra/vc_array_definitions.hpp
  tests/common/include/tests/common/benchmark_find_volume.inl
  tests/common/include/tests/common/benchmark_intersect_all.inl
  tests/common/include/tests/common/benchmark_intersect_surfaces.inl
  tests/common/include/tests/common/core_detector.inl
  tests/common/include/tests/common/core_mask_store.inl
  tests/common/include/tests/common/geometry_volume.inl
  tests/common/include/tests/common/io_read_detector.inl
  tests/common/include/tests/common/test_core.inl
  tests/common/include/tests/common/test_toy_geometry.inl
  tests/common/include/tests/common/tools/create_toy_geometry.hpp
  tests/common/include/tests/common/tools/detector_metadata.hpp
  tests/common/include/tests/common/tools/detector_registry.hpp
  tests/common/include/tests/common/tools/ray_gun.hpp
  tests/common/include/tests/common/tools/test_surfaces.hpp
  tests/common/include/tests/common/tools_cylinder_intersection.inl
  tests/common/include/tests/common/tools_intersection_kernel.inl
  tests/unit_tests/cuda/detector_cuda.cpp
  tests/unit_tests/cuda/detector_cuda_kernel.cu
  tests/unit_tests/cuda/detector_cuda_kernel.hpp
  tests/unit_tests/cuda/mask_store_cuda.cpp
  tests/unit_tests/cuda/mask_store_cuda_kernel.hpp
Labels: enhancement

#201 ref: Remove edges from surfaces
  core/CMakeLists.txt
  core/include/detray/core/detector.hpp
  core/include/detray/core/mask_store.hpp
  core/include/detray/definitions/detail/accessor.hpp
  core/include/detray/geometry/surface.hpp
  core/include/detray/geometry/surface_base.hpp
  core/include/detray/geometry/volume_connector.hpp
  core/include/detray/masks/annulus2.hpp
  core/include/detray/masks/cylinder3.hpp
  core/include/detray/masks/rectangle2.hpp
  core/include/detray/masks/ring2.hpp
  core/include/detray/masks/single3.hpp
  core/include/detray/masks/trapezoid2.hpp
  core/include/detray/masks/unmasked.hpp
  core/include/detray/tools/concentric_cylinder_intersector.hpp
  core/include/detray/tools/cylinder_intersector.hpp
  core/include/detray/tools/geometry_graph.hpp
  core/include/detray/tools/intersection_kernel.hpp
  core/include/detray/tools/navigator.hpp
  core/include/detray/tools/planar_intersector.hpp
  core/include/detray/tools/volume_graph.hpp
  core/include/detray/utils/indexing.hpp
  io/csv/include/detray/io/csv_io.hpp
  tests/common/include/tests/common/benchmark_intersect_surfaces.inl
  tests/common/include/tests/common/benchmark_masks.inl
  tests/common/include/tests/common/check_geometry_linking.inl
  tests/common/include/tests/common/check_geometry_scan.inl
  tests/common/include/tests/common/core_detector.inl
  tests/common/include/tests/common/core_mask_store.inl
  tests/common/include/tests/common/geometry_volume_graph.inl
  tests/common/include/tests/common/masks_annulus2.inl
  tests/common/include/tests/common/masks_cylinder3.inl
  tests/common/include/tests/common/masks_rectangle2.inl
  tests/common/include/tests/common/masks_ring2.inl
  tests/common/include/tests/common/masks_single3.inl
  tests/common/include/tests/common/masks_trapezoid2.inl
  tests/common/include/tests/common/test_core.inl
  tests/common/include/tests/common/test_toy_geometry.inl
  tests/common/include/tests/common/tools/create_toy_geometry.hpp
  tests/common/include/tests/common/tools/ray_gun.hpp
  tests/common/include/tests/common/tools/test_surfaces.hpp
  tests/common/include/tests/common/tools_cylinder_intersection.inl
  tests/common/include/tests/common/tools_intersection_kernel.inl
  tests/common/include/tests/common/tools_planar_intersection.inl
  tests/common/include/tests/common/tools_track.inl
  tests/unit_tests/array/CMakeLists.txt
  tests/unit_tests/array/array_geometry_volume_graph.cpp
  tests/unit_tests/cuda/mask_store_cuda.cpp
  tests/unit_tests/eigen/CMakeLists.txt
  tests/unit_tests/eigen/eigen_geometry_volume_graph.cpp
  tests/unit_tests/smatrix/CMakeLists.txt
  tests/unit_tests/smatrix/smatrix_geometry_volume_graph.cpp
  tests/unit_tests/vc/CMakeLists.txt
  tests/unit_tests/vc/vc_array_geometry_volume_graph.cpp
Labels: refactor

#206 Specialize make tuple for thrust and std
  core/include/detray/definitions/detail/accessor.hpp
Labels: refactor

#207 feat: typed indices
  core/include/detray/core/detector.hpp
  core/include/detray/core/mask_store.hpp
  core/include/detray/core/type_registry.hpp
  core/include/detray/definitions/detail/accessor.hpp
  core/include/detray/geometry/surface.hpp
  core/include/detray/geometry/volume_connector.hpp
  core/include/detray/tools/bin_association.hpp
  core/include/detray/tools/intersection_kernel.hpp
  core/include/detray/tools/volume_graph.hpp
  core/include/detray/utils/generators.hpp
  core/include/detray/utils/indexing.hpp
  tests/common/include/tests/common/test_toy_geometry.inl
  tests/common/include/tests/common/tools_intersection_kernel.inl
  tests/common/include/tests/common/tools_track.inl
  tests/unit_tests/cuda/mask_store_cuda.cpp
  tests/unit_tests/cuda/mask_store_cuda_kernel.cu
  tests/unit_tests/cuda/mask_store_cuda_kernel.hpp
Labels: enhancement, refactor

#209 Propagator with RK stepper
  core/include/detray/core/detector.hpp
  core/include/detray/tools/base_stepper.hpp
  core/include/detray/tools/navigator.hpp
  core/include/detray/tools/propagator.hpp
  core/include/detray/tools/rk_stepper.hpp
  tests/common/include/tests/common/check_geometry_navigation.inl
  tests/common/include/tests/common/tools_navigator.inl
  tests/common/include/tests/common/tools_propagator.inl
  tests/unit_tests/cuda/CMakeLists.txt
  tests/unit_tests/cuda/navigator_cuda.cpp
  tests/unit_tests/cuda/navigator_cuda_kernel.cu
  tests/unit_tests/cuda/navigator_cuda_kernel.hpp
  tests/unit_tests/cuda/propagator_cuda.cpp
  tests/unit_tests/cuda/propagator_cuda_kernel.cu
  tests/unit_tests/cuda/propagator_cuda_kernel.hpp
Labels: enhancement
