Repository acts-project/detray, pull requests merged in 2022-06, with the labels that each got.

#262 Add host accessible memory resource to grid2 buffer
  core/include/detray/grids/grid2.hpp
Labels: enhancement

#266 CMake Requirement Update, main branch (2022.06.10.)
  tests/benchmarks/cuda/CMakeLists.txt
  tests/unit_tests/cuda/CMakeLists.txt
Labels: enhancement

#248 feat: add example of chained actors
  core/include/detray/propagator/aborters.hpp
  core/include/detray/propagator/actor_chain.hpp
  core/include/detray/propagator/base_actor.hpp
  core/include/detray/propagator/base_stepper.hpp
  core/include/detray/propagator/navigation_policies.hpp
  tests/common/include/tests/common/tools/inspectors.hpp
  tests/common/include/tests/common/tools_actor_chain.inl
  tests/common/include/tests/common/tools_guided_navigator.inl
  tests/common/include/tests/common/tools_propagator.inl
  tests/unit_tests/cuda/propagator_cuda.cpp
  tests/unit_tests/cuda/propagator_cuda_kernel.cu
  tests/unit_tests/cuda/propagator_cuda_kernel.hpp
Labels: documentation, refactor

#260 fix: navigation issues
  core/include/detray/intersection/detail/trajectories.hpp
  core/include/detray/intersection/intersection.hpp
  core/include/detray/propagator/aborters.hpp
  core/include/detray/propagator/base_stepper.hpp
  core/include/detray/propagator/navigation_policies.hpp
  core/include/detray/propagator/navigator.hpp
  core/include/detray/propagator/propagator.hpp
  tests/common/include/tests/common/check_geometry_linking.inl
  tests/common/include/tests/common/check_geometry_navigation.inl
  tests/common/include/tests/common/test_telescope_detector.inl
  tests/common/include/tests/common/tools/create_toy_geometry.hpp
  tests/common/include/tests/common/tools/inspectors.hpp
  tests/common/include/tests/common/tools/particle_gun.hpp
  tests/common/include/tests/common/tools/ray_scan_utils.hpp
  tests/common/include/tests/common/tools_guided_navigator.inl
  tests/common/include/tests/common/tools_navigator.inl
  tests/common/include/tests/common/tools_propagator.inl
  tests/common/include/tests/common/tools_stepper.inl
  tests/unit_tests/cuda/navigator_cuda.cpp
  tests/unit_tests/cuda/propagator_cuda.cpp
  tests/unit_tests/cuda/propagator_cuda_kernel.hpp
Labels: bug, refactor
