Repository acts-project/detray, pull requests merged in 2022-04, with the labels that each got.

#238 fix: b field access
  core/include/detray/propagator/rk_stepper.hpp
Labels: bug

#233 Rewrite CI with LLVM
  .github/ci_setup.sh
  .github/workflows/builds.yml
  cmake/detray-compiler-options-cpp.cmake
  core/include/detray/propagator/rk_stepper.hpp
  extern/algebra-plugins/CMakeLists.txt
  extern/benchmark/CMakeLists.txt
  tests/common/include/tests/common/tools_line_stepper.inl
  tests/common/include/tests/common/tools_propagator.inl
  tests/common/include/tests/common/tools_rk_stepper.inl
  tests/common/include/tests/common/tools_stepper.inl
  tests/scripts/analyze_benchmarks.py
  tests/scripts/run_benchmarks.sh
Labels: enhancement, refactor

#234 feat: add actor list
  core/CMakeLists.txt
  core/include/detray/definitions/detail/accessor.hpp
  core/include/detray/propagator/actor_chain.hpp
  core/include/detray/propagator/base_actor.hpp
  core/include/detray/propagator/propagator.hpp
  core/include/detray/propagator/track.hpp
  tests/benchmarks/cuda/benchmark_propagator_cuda.cpp
  tests/benchmarks/cuda/benchmark_propagator_cuda_kernel.cu
  tests/benchmarks/cuda/benchmark_propagator_cuda_kernel.hpp
  tests/common/include/tests/common/tools/helix_gun.hpp
  tests/common/include/tests/common/tools/inspectors.hpp
  tests/common/include/tests/common/tools_actor_chain.inl
  tests/common/include/tests/common/tools_helix_gun.inl
  tests/common/include/tests/common/tools_propagator.inl
  tests/common/include/tests/common/tools_stepper.inl
  tests/unit_tests/array/CMakeLists.txt
  tests/unit_tests/array/array_actor_chain.cpp
  tests/unit_tests/cuda/propagator_cuda.cpp
  tests/unit_tests/cuda/propagator_cuda_kernel.cu
  tests/unit_tests/cuda/propagator_cuda_kernel.hpp
  tests/unit_tests/eigen/CMakeLists.txt
  tests/unit_tests/eigen/eigen_actor_chain.cpp
  tests/unit_tests/smatrix/CMakeLists.txt
  tests/unit_tests/smatrix/smatrix_actor_chain.cpp
  tests/unit_tests/vc/CMakeLists.txt
  tests/unit_tests/vc/vc_array_actor_chain.cpp
Labels: enhancement

#236 feat: add pathlimit aborter
  core/CMakeLists.txt
  core/include/detray/propagator/aborters.hpp
  core/include/detray/propagator/base_stepper.hpp
  core/include/detray/propagator/line_stepper.hpp
  core/include/detray/propagator/propagator.hpp
  core/include/detray/propagator/rk_stepper.hpp
  tests/common/include/tests/common/tools_propagator.inl
  tests/common/include/tests/common/tools_stepper.inl
  tests/unit_tests/cuda/propagator_cuda.cpp
  tests/unit_tests/cuda/propagator_cuda_kernel.cu
  tests/unit_tests/cuda/propagator_cuda_kernel.hpp
  tests/unit_tests/cuda/rk_stepper_cuda.cpp
  tests/unit_tests/cuda/rk_stepper_cuda_kernel.cu
  tests/unit_tests/cuda/rk_stepper_cuda_kernel.hpp
Labels: enhancement

#239 Add covariance transport in RK stepper
  core/CMakeLists.txt
  core/include/detray/definitions/track_parameterization.hpp
  core/include/detray/propagator/base_stepper.hpp
  core/include/detray/propagator/rk_stepper.hpp
  core/include/detray/propagator/rk_stepper.ipp
  core/include/detray/propagator/track.hpp
  core/include/detray/utils/algebra_helpers.hpp
  plugins/algebra/array/include/detray/plugins/algebra/array_definitions.hpp
  plugins/algebra/eigen/include/detray/plugins/algebra/eigen_definitions.hpp
  plugins/algebra/smatrix/include/detray/plugins/algebra/smatrix_definitions.hpp
  plugins/algebra/vc/include/detray/plugins/algebra/vc_array_definitions.hpp
  tests/common/include/tests/common/tools/helix_gun.hpp
  tests/common/include/tests/common/tools_propagator.inl
  tests/common/include/tests/common/tools_stepper.inl
  tests/unit_tests/cuda/propagator_cuda.cpp
  tests/unit_tests/cuda/propagator_cuda_kernel.cu
  tests/unit_tests/cuda/propagator_cuda_kernel.hpp
Labels: enhancement

#242 Feat: navigation policies
  core/CMakeLists.txt
  core/include/detray/definitions/detail/accessor.hpp
  core/include/detray/propagator/aborters.hpp
  core/include/detray/propagator/actor_chain.hpp
  core/include/detray/propagator/base_stepper.hpp
  core/include/detray/propagator/line_stepper.hpp
  core/include/detray/propagator/navigation_policies.hpp
  core/include/detray/propagator/navigator.hpp
  core/include/detray/propagator/propagator.hpp
  core/include/detray/propagator/rk_stepper.hpp
  core/include/detray/propagator/rk_stepper.ipp
  core/include/detray/tools/associator.hpp
  core/include/detray/tools/bin_association.hpp
  core/include/detray/tools/generators.hpp
  tests/benchmarks/cuda/benchmark_propagator_cuda_kernel.hpp
  tests/common/include/tests/common/check_geometry_navigation.inl
  tests/common/include/tests/common/test_telescope_detector.inl
  tests/common/include/tests/common/tools/create_telescope_detector.hpp
  tests/common/include/tests/common/tools_guided_navigator.inl
  tests/common/include/tests/common/tools_navigator.inl
  tests/common/include/tests/common/tools_propagator.inl
  tests/common/include/tests/common/tools_stepper.inl
  tests/unit_tests/cuda/navigator_cuda.cpp
  tests/unit_tests/cuda/navigator_cuda_kernel.cu
  tests/unit_tests/cuda/navigator_cuda_kernel.hpp
  tests/unit_tests/cuda/rk_stepper_cuda.cpp
  tests/unit_tests/cuda/rk_stepper_cuda_kernel.cu
  tests/unit_tests/cuda/rk_stepper_cuda_kernel.hpp
Labels: enhancement

#252 Grid2 Const Conversion, main branch (2022.04.27.)
  core/CMakeLists.txt
  core/include/detray/grids/axis.hpp
  core/include/detray/grids/grid2.hpp
  core/include/detray/utils/type_traits.hpp
  tests/unit_tests/cuda/grids_grid2_cuda.cpp
Labels: enhancement

#253 Grid2 Const Correctness, main branch (2022.04.28.)
  core/include/detray/grids/grid2.hpp
  tests/unit_tests/cuda/grids_grid2_cuda_kernel.cu
Labels: bug
