Repository acts-project/detray, pull requests merged in 2022-09, with the labels that each got.

#297 Change CMake logic for integrating covfie
  CMakeLists.txt
  extern/covfie/CMakeLists.txt
Labels: refactor

#299 CMake 3.24 Compatibility, main branch (2022.09.13.)
  extern/actsvg/CMakeLists.txt
  extern/algebra-plugins/CMakeLists.txt
  extern/benchmark/CMakeLists.txt
  extern/covfie/CMakeLists.txt
  extern/dfelibs/CMakeLists.txt
  extern/googletest/CMakeLists.txt
  extern/thrust/CMakeLists.txt
  extern/vecmem/CMakeLists.txt
Labels: enhancement

#298 Thrust Setup Update, main branch (2022.09.13.)
  CMakeLists.txt
Labels: bug

#304 Allow use of system libraries by default
  CMakeLists.txt
Labels: enhancement
