Repository acts-project/detray, pull requests merged in 2022-03, with the labels that each got.

#212 chore: clean clang warnings
  core/include/detray/core/detector.hpp
  core/include/detray/core/transform_store.hpp
  core/include/detray/definitions/detail/accessor.hpp
  core/include/detray/geometry/volume.hpp
  core/include/detray/tools/concentric_cylinder_intersector.hpp
  core/include/detray/tools/cylinder_intersector.hpp
  core/include/detray/tools/intersection_kernel.hpp
  core/include/detray/tools/navigator.hpp
  core/include/detray/tools/volume_graph.hpp
  core/include/detray/utils/enumerate.hpp
  tests/benchmarks/core/benchmark_grids.cpp
  tests/common/include/tests/common/benchmark_intersect_surfaces.inl
  tests/common/include/tests/common/core_detector.inl
  tests/common/include/tests/common/core_transform_store.inl
  tests/common/include/tests/common/masks_single3.inl
  tests/common/include/tests/common/masks_unmasked.inl
  tests/common/include/tests/common/test_core.inl
  tests/common/include/tests/common/test_defs.hpp
  tests/common/include/tests/common/tools/helix_gun.hpp
  tests/common/include/tests/common/tools/ray_scan_utils.hpp
  tests/common/include/tests/common/tools/test_surfaces.hpp
  tests/common/include/tests/common/tools_cylinder_intersection.inl
  tests/common/include/tests/common/tools_intersection_kernel.inl
  tests/common/include/tests/common/tools_planar_intersection.inl
  tests/common/include/tests/common/tools_track.inl
Labels: bug

#215 Grid2 Const Correctness, main branch (2022.02.28.)
  core/include/detray/core/surfaces_finder.hpp
  core/include/detray/grids/axis.hpp
  core/include/detray/grids/grid2.hpp
  core/include/detray/grids/populator.hpp
  tests/unit_tests/cuda/grids_grid2_cuda.cpp
  tests/unit_tests/cuda/grids_grid2_cuda_kernel.cu
  tests/unit_tests/cuda/grids_grid2_cuda_kernel.hpp
  tests/unit_tests/cuda/mask_store_cuda.cpp
  tests/unit_tests/cuda/surfaces_finder_cuda.cpp
  tests/unit_tests/cuda/tuple_test_cuda.cpp
Labels: refactor

#216 CUDA propagator benchmark
  core/include/detray/tools/navigator.hpp
  tests/benchmarks/CMakeLists.txt
  tests/benchmarks/cuda/CMakeLists.txt
  tests/benchmarks/cuda/benchmark_propagator_cuda.cpp
  tests/benchmarks/cuda/benchmark_propagator_cuda_kernel.cu
  tests/benchmarks/cuda/benchmark_propagator_cuda_kernel.hpp
  tests/unit_tests/cuda/navigator_cuda.cpp
  tests/unit_tests/cuda/propagator_cuda.cpp
Labels: enhancement

#220 exp: trust based navigation
  .github/workflows/builds.yml
  core/include/detray/core/detector.hpp
  core/include/detray/definitions/detail/accessor.hpp
  core/include/detray/definitions/units.hpp
  core/include/detray/tools/base_stepper.hpp
  core/include/detray/tools/line_stepper.hpp
  core/include/detray/tools/navigator.hpp
  core/include/detray/tools/propagator.hpp
  core/include/detray/tools/rk_stepper.hpp
  tests/benchmarks/cuda/benchmark_propagator_cuda.cpp
  tests/benchmarks/cuda/benchmark_propagator_cuda_kernel.cu
  tests/common/include/tests/common/check_geometry_navigation.inl
  tests/common/include/tests/common/tools/inspectors.hpp
  tests/common/include/tests/common/tools_line_stepper.inl
  tests/common/include/tests/common/tools_navigator.inl
  tests/common/include/tests/common/tools_propagator.inl
  tests/common/include/tests/common/tools_rk_stepper.inl
  tests/unit_tests/cuda/navigator_cuda.cpp
  tests/unit_tests/cuda/navigator_cuda_kernel.cu
  tests/unit_tests/cuda/propagator_cuda.cpp
  tests/unit_tests/cuda/rk_stepper_cuda.cpp
  tests/unit_tests/cuda/rk_stepper_cuda_kernel.cu
  tests/unit_tests/cuda/rk_stepper_cuda_kernel.hpp
Labels: bug, enhancement

#179 ref: Use adj matrix in geometry graph
  core/include/detray/tools/volume_graph.hpp
  tests/common/include/tests/common/check_geometry_linking.inl
  tests/common/include/tests/common/check_geometry_scan.inl
  tests/common/include/tests/common/geometry_volume_graph.inl
  tests/common/include/tests/common/tools/hash_tree.hpp
  tests/common/include/tests/common/tools/ray_scan_utils.hpp
  tests/unit_tests/core/CMakeLists.txt
  tests/unit_tests/core/tools_hash_tree.cpp
Labels: refactor

#197 feat: add telescope detector and guided navigation example
  core/include/detray/masks/masks.hpp
  core/include/detray/masks/unmasked.hpp
  core/include/detray/tools/line_stepper.hpp
  core/include/detray/tools/navigator.hpp
  tests/common/include/tests/common/masks_unmasked.inl
  tests/common/include/tests/common/test_telescope_detector.inl
  tests/common/include/tests/common/tools/create_telescope_detector.hpp
  tests/common/include/tests/common/tools/detector_metadata.hpp
  tests/common/include/tests/common/tools_guided_navigator.inl
  tests/common/include/tests/common/tools_planar_intersection.inl
  tests/unit_tests/array/CMakeLists.txt
  tests/unit_tests/array/array_guided_navigator.cpp
  tests/unit_tests/array/array_telescope_detector.cpp
  tests/unit_tests/eigen/CMakeLists.txt
  tests/unit_tests/eigen/eigen_guided_navigator.cpp
  tests/unit_tests/eigen/eigen_telescope_detector.cpp
  tests/unit_tests/smatrix/CMakeLists.txt
  tests/unit_tests/smatrix/smatrix_guided_navigator.cpp
  tests/unit_tests/smatrix/smatrix_telescope_detector.cpp
  tests/unit_tests/vc/CMakeLists.txt
  tests/unit_tests/vc/vc_array_guided_navigator.cpp
  tests/unit_tests/vc/vc_array_telescope_detector.cpp
Labels: enhancement

#227 Update algebra-plugins to v0.8.0
  extern/algebra-plugins/CMakeLists.txt
Labels: enhancement

#229 Fix a bug in cuda navigator
  core/include/detray/tools/line_stepper.hpp
  tests/unit_tests/cuda/navigator_cuda.cpp
  tests/unit_tests/cuda/navigator_cuda_kernel.cu
  tests/unit_tests/cuda/navigator_cuda_kernel.hpp
Labels: bug

#225 Fix Warnings from Clang compilation
  cmake/detray-compiler-options-cuda.cmake
  plugins/algebra/eigen/CMakeLists.txt
  tests/benchmarks/cuda/benchmark_propagator_cuda_kernel.hpp
  tests/unit_tests/cuda/propagator_cuda_kernel.hpp
  tests/unit_tests/cuda/transform_store_cuda.cpp
Labels: bug

#228 Feat: add constrained stepping
  core/CMakeLists.txt
  core/include/detray/field/constant_magnetic_field.hpp
  core/include/detray/tools/base_stepper.hpp
  core/include/detray/tools/constrained_step.hpp
  core/include/detray/tools/line_stepper.hpp
  core/include/detray/tools/navigator.hpp
  core/include/detray/tools/propagator.hpp
  core/include/detray/tools/rk_stepper.hpp
  core/include/detray/utils/c_step.hpp
  tests/common/include/tests/common/check_geometry_navigation.inl
  tests/common/include/tests/common/tools/inspectors.hpp
  tests/common/include/tests/common/tools_guided_navigator.inl
  tests/common/include/tests/common/tools_line_stepper.inl
  tests/common/include/tests/common/tools_navigator.inl
  tests/common/include/tests/common/tools_propagator.inl
  tests/common/include/tests/common/tools_rk_stepper.inl
  tests/common/include/tests/common/tools_stepper.inl
  tests/unit_tests/array/CMakeLists.txt
  tests/unit_tests/array/array_line_stepper.cpp
  tests/unit_tests/array/array_stepper.cpp
  tests/unit_tests/cuda/propagator_cuda_kernel.hpp
  tests/unit_tests/eigen/CMakeLists.txt
  tests/unit_tests/eigen/eigen_line_stepper.cpp
  tests/unit_tests/eigen/eigen_stepper.cpp
  tests/unit_tests/smatrix/CMakeLists.txt
  tests/unit_tests/smatrix/smatrix_line_stepper.cpp
  tests/unit_tests/smatrix/smatrix_stepper.cpp
  tests/unit_tests/vc/CMakeLists.txt
  tests/unit_tests/vc/vc_array_line_stepper.cpp
  tests/unit_tests/vc/vc_array_stepper.cpp
Labels: enhancement

#230 Reorganize plugin definitions
  core/include/detray/tools/constrained_step.hpp
  core/include/detray/tools/track_parameterization.hpp
  plugins/algebra/array/include/detray/plugins/algebra/array_definitions.hpp
  plugins/algebra/eigen/include/detray/plugins/algebra/eigen_definitions.hpp
  plugins/algebra/smatrix/include/detray/plugins/algebra/smatrix_definitions.hpp
  plugins/algebra/vc/include/detray/plugins/algebra/vc_array_definitions.hpp
Labels: refactor

#232 Ref: move intersection enum to own namespace
  core/include/detray/intersection/concentric_cylinder_intersector.hpp
  core/include/detray/intersection/cylinder_intersector.hpp
  core/include/detray/intersection/intersection.hpp
  core/include/detray/intersection/intersection_kernel.hpp
  core/include/detray/intersection/planar_intersector.hpp
  core/include/detray/masks/annulus2.hpp
  core/include/detray/masks/cylinder3.hpp
  core/include/detray/masks/rectangle2.hpp
  core/include/detray/masks/ring2.hpp
  core/include/detray/masks/single3.hpp
  core/include/detray/masks/trapezoid2.hpp
  core/include/detray/masks/unmasked.hpp
  core/include/detray/propagator/navigator.hpp
  core/include/detray/propagator/propagator.hpp
  tests/benchmarks/cuda/benchmark_propagator_cuda_kernel.cu
  tests/benchmarks/cuda/benchmark_propagator_cuda_kernel.hpp
  tests/common/include/tests/common/benchmark_intersect_all.inl
  tests/common/include/tests/common/benchmark_intersect_surfaces.inl
  tests/common/include/tests/common/benchmark_masks.inl
  tests/common/include/tests/common/masks_annulus2.inl
  tests/common/include/tests/common/masks_cylinder3.inl
  tests/common/include/tests/common/masks_rectangle2.inl
  tests/common/include/tests/common/masks_ring2.inl
  tests/common/include/tests/common/masks_single3.inl
  tests/common/include/tests/common/masks_trapezoid2.inl
  tests/common/include/tests/common/masks_unmasked.inl
  tests/common/include/tests/common/test_core.inl
  tests/common/include/tests/common/tools/inspectors.hpp
  tests/common/include/tests/common/tools/ray_gun.hpp
  tests/common/include/tests/common/tools/ray_scan_utils.hpp
  tests/common/include/tests/common/tools_cylinder_intersection.inl
  tests/common/include/tests/common/tools_planar_intersection.inl
  tests/unit_tests/cuda/mask_store_cuda.cpp
  tests/unit_tests/cuda/mask_store_cuda_kernel.cu
  tests/unit_tests/cuda/mask_store_cuda_kernel.hpp
  tests/unit_tests/cuda/navigator_cuda_kernel.cu
  tests/unit_tests/cuda/navigator_cuda_kernel.hpp
  tests/unit_tests/cuda/propagator_cuda.cpp
  tests/unit_tests/cuda/propagator_cuda_kernel.cu
  tests/unit_tests/cuda/propagator_cuda_kernel.hpp
Labels: refactor
