Repository acts-project/detray, pull requests merged in 2023-04, with the labels that each got.

#426 Add make_curvilinear_unit_vector function and fix some bugs
  core/CMakeLists.txt
  core/include/detray/propagator/propagator.hpp
  core/include/detray/utils/axis_rotation.hpp
  core/include/detray/utils/unit_vectors.hpp
  tests/common/include/tests/common/axis_rotation.inl
  tests/common/include/tests/common/utils_unit_vectors.inl
  tests/unit_tests/cpu/array/CMakeLists.txt
  tests/unit_tests/cpu/array/array_unit_vectors.cpp
  tests/unit_tests/cpu/eigen/CMakeLists.txt
  tests/unit_tests/cpu/eigen/eigen_unit_vectors.cpp
  tests/unit_tests/cpu/smatrix/CMakeLists.txt
  tests/unit_tests/cpu/smatrix/smatrix_unit_vectors.cpp
  tests/unit_tests/cpu/vc/CMakeLists.txt
  tests/unit_tests/cpu/vc/vc_array_unit_vectors.cpp
  utils/include/detray/simulation/random_scatterer.hpp
Labels: enhancement

#432 CI Benchmark Fix, main branch (2023.03.04.)
  tests/scripts/run_benchmarks.sh
Labels: bug, priority: high

#431 detray::core Refactor, main branch (2023.04.03.)
  core/CMakeLists.txt
  core/include/detray/definitions/algebra.hpp
  core/include/detray/definitions/grid_axis.hpp
  core/include/detray/definitions/math.hpp
  core/include/detray/definitions/pdg_particle.hpp
  core/include/detray/geometry/detector_volume.hpp
  core/include/detray/grids/axis.hpp
  core/include/detray/intersection/intersection.hpp
  core/include/detray/masks/single3D.hpp
  core/include/detray/masks/unbounded.hpp
  core/include/detray/materials/predefined_materials.hpp
  core/include/detray/propagator/actors/pointwise_material_interactor.hpp
  core/include/detray/propagator/constrained_step.hpp
  core/include/detray/propagator/navigation_policies.hpp
  core/include/detray/propagator/propagator.hpp
  core/include/detray/surface_finders/grid/detail/axis_binning.hpp
  core/include/detray/surface_finders/grid/detail/axis_helpers.hpp
  core/include/detray/tools/associator.hpp
  core/include/detray/tools/local_object_finder.hpp
  core/include/detray/tools/surface_factory.hpp
  core/include/detray/tools/surface_factory_interface.hpp
  core/include/detray/tracks/bound_track_parameters.hpp
  core/include/detray/tracks/free_track_parameters.hpp
  core/include/detray/utils/matrix_helper.hpp
  core/include/detray/utils/quadratic_equation.hpp
  core/include/detray/utils/unit_vectors.hpp
  tests/benchmarks/core/CMakeLists.txt
  tests/benchmarks/core/benchmark_grids.cpp
  tests/common/include/tests/common/test_defs.hpp
  tests/unit_tests/core/CMakeLists.txt
  tests/unit_tests/core/utils_quadratic_equation.cpp
  tests/unit_tests/device/cuda/CMakeLists.txt
Labels: bug, refactor

#434 detray::io Refactor, main branch (2023.04.04.)
  CMakeLists.txt
  README.md
  cmake/detray-config.cmake.in
  io/CMakeLists.txt
  io/csv/CMakeLists.txt
  io/include/detray/io/csv_io.hpp
  io/include/detray/io/csv_io_types.hpp
  io/include/detray/io/io_payload.hpp
  io/include/detray/io/json_algebra_io.hpp
  io/include/detray/io/json_defs.hpp
  io/include/detray/io/json_geometry_io.hpp
  io/include/detray/io/json_grids_io.hpp
  io/include/detray/io/json_io.hpp
  io/include/detray/io/json_material_io.hpp
  io/include/detray/io/utils.hpp
  io/json/CMakeLists.txt
  io/payload/CMakeLists.txt
  tests/unit_tests/cpu/array/CMakeLists.txt
  tests/unit_tests/cpu/eigen/CMakeLists.txt
  tests/unit_tests/cpu/smatrix/CMakeLists.txt
  tests/unit_tests/cpu/vc/CMakeLists.txt
Labels: bug, refactor

#436 detray::utils Refactor, main branch (2023.04.05.)
  tests/common/include/tests/common/test_toy_geometry.inl
  tests/common/include/tests/common/tools_navigator.inl
  utils/CMakeLists.txt
  utils/include/detray/detectors/create_telescope_detector.hpp
  utils/include/detray/detectors/create_toy_geometry.hpp
  utils/include/detray/simulation/event_generator/random_track_generator.hpp
  utils/include/detray/simulation/event_generator/uniform_track_generator.hpp
  utils/include/detray/simulation/event_writer.hpp
  utils/include/detray/simulation/measurement_smearer.hpp
  utils/include/detray/simulation/random_scatterer.hpp
Labels: bug, refactor

#428 feat: json geometry writer
  core/include/detray/geometry/detector_volume.hpp
  core/include/detray/geometry/surface.hpp
  core/include/detray/materials/material.hpp
  io/CMakeLists.txt
  io/include/detray/io/common/detail/file_handle.hpp
  io/include/detray/io/common/detail/utils.hpp
  io/include/detray/io/common/geometry_writer.hpp
  io/include/detray/io/common/payloads.hpp
  io/include/detray/io/csv/csv_io.hpp
  io/include/detray/io/csv/csv_io_types.hpp
  io/include/detray/io/io_payload.hpp
  io/include/detray/io/json/json.hpp
  io/include/detray/io/json/json_algebra_io.hpp
  io/include/detray/io/json/json_geometry_io.hpp
  io/include/detray/io/json/json_geometry_writer.hpp
  io/include/detray/io/json/json_grids_io.hpp
  io/include/detray/io/json/json_material_io.hpp
  io/include/detray/io/json/json_serializers.hpp
  io/include/detray/io/json_geometry_io.hpp
  io/include/detray/io/json_io.hpp
  io/include/detray/io/json_material_io.hpp
  tests/common/include/tests/common/check_simulation.inl
  tests/common/include/tests/common/test_telescope_detector.inl
  tests/common/include/tests/common/tools/read_geometry.hpp
  tests/unit_tests/io/CMakeLists.txt
  tests/unit_tests/io/io_json_geometry_writer.cpp
  tests/unit_tests/io/io_json_payload.cpp
  utils/include/detray/detectors/detector_metadata.hpp
  utils/include/detray/simulation/event_writer.hpp
Labels: enhancement, priority: high

#440 Fix `find_package` syntax for actsvg
  CMakeLists.txt
Labels: bug

#415 feat: Implement `detray::tuple`
  core/include/detray/core/detail/container_views.hpp
  core/include/detray/definitions/containers.hpp
  core/include/detray/intersection/concentric_cylinder_intersector.hpp
  core/include/detray/intersection/cylinder_intersector.hpp
  core/include/detray/masks/annulus2D.hpp
  core/include/detray/masks/cuboid3D.hpp
  core/include/detray/masks/cylinder2D.hpp
  core/include/detray/masks/cylinder3D.hpp
  core/include/detray/masks/line.hpp
  core/include/detray/masks/rectangle2D.hpp
  core/include/detray/masks/ring2D.hpp
  core/include/detray/masks/single3D.hpp
  core/include/detray/masks/trapezoid2D.hpp
  core/include/detray/masks/unmasked.hpp
  core/include/detray/tools/grid_factory.hpp
  core/include/detray/utils/quadratic_equation.hpp
  core/include/detray/utils/tuple.hpp
  core/include/detray/utils/tuple_helpers.hpp
  core/include/detray/utils/type_registry.hpp
  tests/benchmarks/cuda/benchmark_propagator_cuda.cpp
  tests/benchmarks/cuda/benchmark_propagator_cuda_kernel.cu
  tests/benchmarks/cuda/benchmark_propagator_cuda_kernel.hpp
  tests/common/include/tests/common/core_container.inl
  tests/common/include/tests/common/test_base/propagator_test.hpp
  tests/common/include/tests/common/tools/test_surfaces.hpp
  tests/unit_tests/core/tuple_helpers.cpp
  tests/unit_tests/core/utils_quadratic_equation.cpp
  tests/unit_tests/device/cuda/container_cuda_kernel.hpp
  tests/unit_tests/device/cuda/mask_store_cuda_kernel.hpp
  tests/unit_tests/device/cuda/propagator_cuda.cpp
  tests/unit_tests/device/cuda/propagator_cuda_kernel.cu
  tests/unit_tests/device/sycl/propagator.sycl
  tests/unit_tests/device/sycl/propagator_kernel.sycl
Labels: enhancement

#441 ref: Reduce size of navigator memory alloc
  core/include/detray/core/detector.hpp
  core/include/detray/geometry/detector_volume.hpp
  core/include/detray/propagator/navigator.hpp
  core/include/detray/surface_finders/brute_force_finder.hpp
  core/include/detray/surface_finders/grid/grid.hpp
  core/include/detray/tools/volume_builder.hpp
  utils/include/detray/detectors/create_telescope_detector.hpp
Labels: refactor, priority: low

#437 Refactor CPU Benchmarks, main branch (2023.04.05.)
  CMakeLists.txt
  tests/CMakeLists.txt
  tests/benchmarks/CMakeLists.txt
  tests/benchmarks/array/CMakeLists.txt
  tests/benchmarks/array/array_find_volume.cpp
  tests/benchmarks/array/array_intersect_all.cpp
  tests/benchmarks/array/array_intersect_surfaces.cpp
  tests/benchmarks/array/array_masks.cpp
  tests/benchmarks/core/CMakeLists.txt
  tests/benchmarks/core/benchmark_grids.cpp
  tests/benchmarks/cpu/CMakeLists.txt
  tests/benchmarks/cpu/find_volume.cpp
  tests/benchmarks/cpu/grids.cpp
  tests/benchmarks/cpu/intersect_all.cpp
  tests/benchmarks/cpu/intersect_surfaces.cpp
  tests/benchmarks/cpu/masks.cpp
  tests/benchmarks/eigen/CMakeLists.txt
  tests/benchmarks/eigen/eigen_find_volume.cpp
  tests/benchmarks/eigen/eigen_intersect_all.cpp
  tests/benchmarks/eigen/eigen_intersect_surfaces.cpp
  tests/benchmarks/eigen/eigen_masks.cpp
  tests/benchmarks/smatrix/CMakeLists.txt
  tests/benchmarks/smatrix/smatrix_find_volume.cpp
  tests/benchmarks/smatrix/smatrix_intersect_all.cpp
  tests/benchmarks/smatrix/smatrix_intersect_surfaces.cpp
  tests/benchmarks/smatrix/smatrix_masks.cpp
  tests/benchmarks/vc/CMakeLists.txt
  tests/benchmarks/vc/vc_array_find_volume.cpp
  tests/benchmarks/vc/vc_array_intersect_all.cpp
  tests/benchmarks/vc/vc_array_intersect_surfaces.cpp
  tests/benchmarks/vc/vc_array_masks.cpp
  tests/common/include/tests/common/benchmark_intersect_all.inl
  tests/include/detray/test/planes_along_direction.hpp
  tests/include/detray/test/types.hpp
  tests/scripts/run_benchmarks.sh
Labels: refactor
