Repository acts-project/detray, pull requests merged in 2023-08, with the labels that each got.

#521 ref: grid payloads cleanup
  io/include/detray/io/common/detail/definitions.hpp
  io/include/detray/io/common/geometry_reader.hpp
  io/include/detray/io/common/geometry_writer.hpp
  io/include/detray/io/common/grid_writer.hpp
  io/include/detray/io/common/homogeneous_material_reader.hpp
  io/include/detray/io/common/homogeneous_material_writer.hpp
  io/include/detray/io/common/io_interface.hpp
  io/include/detray/io/common/payloads.hpp
  io/include/detray/io/json/json_common_io.hpp
  io/include/detray/io/json/json_geometry_io.hpp
  io/include/detray/io/json/json_grids_io.hpp
  io/include/detray/io/json/json_material_io.hpp
  io/include/detray/io/json/json_serializers.hpp
  tests/unit_tests/io/io_json_payload.cpp
Labels: refactor, priority: high

#530 Avoid multiple definitions
  io/include/detray/io/common/detail/file_handle.hpp
  io/include/detray/io/json/json_algebra_io.hpp
  io/include/detray/io/json/json_common_io.hpp
  io/include/detray/io/json/json_geometry_io.hpp
  io/include/detray/io/json/json_grids_io.hpp
  io/include/detray/io/json/json_material_io.hpp
  io/include/detray/io/json/json_reader.hpp
Labels: bug, priority: high

#522 ref: pool detector and navigation checks in a single tool
  core/include/detray/intersection/detail/trajectories.hpp
  core/include/detray/intersection/intersection.hpp
  core/include/detray/propagator/line_stepper.hpp
  core/include/detray/propagator/navigator.hpp
  core/include/detray/tracks/free_track_parameters.hpp
  core/include/detray/utils/inspectors.hpp
  io/include/detray/io/common/geometry_reader.hpp
  tests/CMakeLists.txt
  tests/checks/CMakeLists.txt
  tests/checks/include/detray/checks/detector_consistency.hpp
  tests/checks/src/CMakeLists.txt
  tests/checks/src/checks_main.cpp
  tests/common/include/tests/common/tools/ray_scan_utils.hpp
  tests/unit_tests/cpu/CMakeLists.txt
  tests/unit_tests/cpu/check_geometry_linking.cpp
  tests/unit_tests/cpu/check_geometry_navigation.cpp
  tests/unit_tests/cpu/check_geometry_scan.cpp
  tests/unit_tests/cpu/tools_guided_navigator.cpp
  tests/unit_tests/cpu/tools_stepper.cpp
  tests/validation/CMakeLists.txt
  tests/validation/include/detray/validation/detail/navigation_check_helper.hpp
  tests/validation/include/detray/validation/detail/register_checks.hpp
  tests/validation/include/detray/validation/detector_consistency.hpp
  tests/validation/include/detray/validation/detector_helix_scan.hpp
  tests/validation/include/detray/validation/detector_ray_scan.hpp
  tests/validation/include/detray/validation/helix_navigation.hpp
  tests/validation/include/detray/validation/straight_line_navigation.hpp
  tests/validation/src/CMakeLists.txt
  tests/validation/src/detector_validation.cpp
  tests/validation/src/simulation_validation.cpp
  tests/validation/src/telescope_detector_validation.cpp
  tests/validation/src/toy_detector_validation.cpp
  tests/validation/src/wire_chamber_validation.cpp
Labels: enhancement, refactor, priority: medium
