Repository acts-project/detray, pull requests merged in 2023-11, with the labels that each got.

#583 feat integrate grid svg
  core/include/detray/intersection/detail/trajectories.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/grid.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/intersection.hpp
  plugins/svgtools/include/detray/plugins/svgtools/illustrator.hpp
  plugins/svgtools/include/detray/plugins/svgtools/meta/display/tracking.hpp
  plugins/svgtools/include/detray/plugins/svgtools/meta/proto/intersection.hpp
  plugins/svgtools/include/detray/plugins/svgtools/styling/styling.hpp
  tests/validation/src/detector_display.cpp
  tests/validation/src/detector_validation.cpp
Labels: enhancement, refactor, priority: low

#557 feat: material maps
  core/include/detray/core/detector.hpp
  core/include/detray/core/detector_metadata.hpp
  core/include/detray/geometry/surface.hpp
  core/include/detray/materials/material.hpp
  core/include/detray/materials/material_map.hpp
  core/include/detray/materials/material_rod.hpp
  core/include/detray/materials/material_slab.hpp
  core/include/detray/propagator/actors/pointwise_material_interactor.hpp
  core/include/detray/propagator/navigator.hpp
  core/include/detray/surface_finders/brute_force_finder.hpp
  core/include/detray/surface_finders/grid/grid.hpp
  core/include/detray/surface_finders/grid/grid_collection.hpp
  core/include/detray/tools/material_builder.hpp
  core/include/detray/tools/material_factory.hpp
  core/include/detray/tools/volume_builder.hpp
  io/include/detray/io/common/detail/type_traits.hpp
  io/include/detray/io/common/detector_writer.hpp
  io/include/detray/io/common/homogeneous_material_reader.hpp
  io/include/detray/io/common/homogeneous_material_writer.hpp
  tests/common/include/tests/common/test_toy_detector.hpp
  tests/unit_tests/cpu/CMakeLists.txt
  tests/unit_tests/cpu/material_maps.cpp
  tests/unit_tests/cpu/test_toy_geometry.cpp
  tests/unit_tests/cpu/tools_particle_gun.cpp
  tests/unit_tests/cpu/tools_propagator.cpp
  tests/unit_tests/io/io_json_detector_reader.cpp
  tests/validation/include/detray/validation/detector_material_scan.hpp
  tutorials/include/detray/tutorial/detector_metadata.hpp
  utils/include/detray/detectors/create_toy_geometry.hpp
  utils/include/detray/detectors/create_wire_chamber.hpp
  utils/include/detray/detectors/detector_helper.hpp
  utils/include/detray/detectors/itk_metadata.hpp
  utils/include/detray/detectors/telescope_metadata.hpp
  utils/include/detray/detectors/toy_metadata.hpp
Labels: enhancement, priority: high

#594 ref: remove the use of infinitiy
  core/include/detray/definitions/indexing.hpp
  core/include/detray/geometry/detector_volume.hpp
  core/include/detray/geometry/surface.hpp
  core/include/detray/intersection/detail/trajectories.hpp
  core/include/detray/masks/annulus2D.hpp
  core/include/detray/masks/unmasked.hpp
  core/include/detray/materials/material.hpp
  core/include/detray/propagator/navigator.hpp
  core/include/detray/tools/bounding_volume.hpp
  core/include/detray/tools/surface_factory.hpp
  core/include/detray/tools/surface_factory_interface.hpp
  core/include/detray/utils/consistency_checker.hpp
  core/include/detray/utils/inspectors.hpp
  core/include/detray/utils/invalid_values.hpp
  plugins/svgtools/include/detray/plugins/svgtools/utils/link_utils.hpp
  tests/common/include/tests/common/tools/hash_tree.hpp
  tests/unit_tests/core/utils_invalid_values.cpp
  tests/unit_tests/cpu/coordinate_cylindrical2.cpp
  tests/unit_tests/cpu/core_detector.cpp
  tests/unit_tests/cpu/masks_unmasked.cpp
  tests/unit_tests/cpu/test_core.cpp
  tests/unit_tests/cpu/tools_helix_intersectors.cpp
  tests/unit_tests/cpu/tools_navigator.cpp
Labels: bug, refactor, priority: low

#588 fix: material json schema
  tests/validation/python/validation/json_schema/homogeneous_material.py
Labels: bug, priority: high

#587 feat: material maps writer
  core/include/detray/core/detail/multi_store.hpp
  io/include/detray/io/common/detail/grid_writer.hpp
  io/include/detray/io/common/detail/type_traits.hpp
  io/include/detray/io/common/detector_writer.hpp
  io/include/detray/io/common/homogeneous_material_writer.hpp
  io/include/detray/io/common/material_map_writer.hpp
  io/include/detray/io/common/surface_grid_writer.hpp
  io/include/detray/io/json/json_writer.hpp
  tests/unit_tests/io/io_json_detector_writer.cpp
Labels: enhancement, refactor, priority: high

#592 fix: annulus svg
  core/include/detray/masks/annulus2D.hpp
  core/include/detray/masks/masks.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/surface.hpp
  plugins/svgtools/include/detray/plugins/svgtools/utils/surface_kernels.hpp
  tests/unit_tests/svgtools/masks.cpp
  tests/validation/src/detector_display.cpp
Labels: bug, refactor, priority: medium

#597 Add material getter in random scatterer
  utils/include/detray/simulation/random_scatterer.hpp
Labels: priority: high

#596 ref: Use proto detector and proto volumes in svgtools illustrator
  core/include/detray/core/detector.hpp
  core/include/detray/geometry/detail/surface_kernels.hpp
  core/include/detray/geometry/detector_volume.hpp
  core/include/detray/geometry/surface.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/detector.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/grid.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/information_section.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/portal.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/surface.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/volume.hpp
  plugins/svgtools/include/detray/plugins/svgtools/illustrator.hpp
  plugins/svgtools/include/detray/plugins/svgtools/styling/colors.hpp
  plugins/svgtools/include/detray/plugins/svgtools/styling/styling.hpp
  tests/unit_tests/svgtools/detectors.cpp
  tests/unit_tests/svgtools/grids.cpp
  tests/unit_tests/svgtools/groups.cpp
  tests/unit_tests/svgtools/intersections.cpp
  tests/unit_tests/svgtools/surfaces.cpp
  tests/unit_tests/svgtools/trajectories.cpp
  tests/unit_tests/svgtools/volumes.cpp
  tests/unit_tests/svgtools/web.cpp
  tests/validation/include/detray/validation/detail/svg_display.hpp
  tests/validation/include/detray/validation/detector_helix_scan.hpp
  tests/validation/include/detray/validation/detector_ray_scan.hpp
  tests/validation/include/detray/validation/helix_navigation.hpp
  tests/validation/include/detray/validation/straight_line_navigation.hpp
  tests/validation/src/detector_display.cpp
Labels: refactor, priority: low

#599 feat: display connected grids in svg
  plugins/svgtools/include/detray/plugins/svgtools/conversion/detector.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/grid.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/intersection.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/landmark.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/portal.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/surface.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/trajectory.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/volume.hpp
  plugins/svgtools/include/detray/plugins/svgtools/illustrator.hpp
  plugins/svgtools/include/detray/plugins/svgtools/styling/styling.hpp
  tests/unit_tests/svgtools/grids.cpp
  tests/unit_tests/svgtools/groups.cpp
  tests/unit_tests/svgtools/surfaces.cpp
  tests/unit_tests/svgtools/trajectories.cpp
  tests/unit_tests/svgtools/volumes.cpp
  tests/unit_tests/svgtools/web.cpp
  tests/validation/include/detray/validation/detail/svg_display.hpp
  tests/validation/src/detector_display.cpp
Labels: enhancement, priority: low

#601 feat: add more configuration options for svg and add eta lines
  core/include/detray/core/detail/data_context.hpp
  core/include/detray/surface_finders/grid/grid.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/detector.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/grid.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/information_section.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/intersection.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/landmark.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/link.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/point.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/portal.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/surface.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/trajectory.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/volume.hpp
  plugins/svgtools/include/detray/plugins/svgtools/illustrator.hpp
  plugins/svgtools/include/detray/plugins/svgtools/meta/display/geometry.hpp
  plugins/svgtools/include/detray/plugins/svgtools/meta/proto/eta_lines.hpp
  plugins/svgtools/include/detray/plugins/svgtools/meta/proto/information_section.hpp
  plugins/svgtools/include/detray/plugins/svgtools/meta/proto/intersection.hpp
  plugins/svgtools/include/detray/plugins/svgtools/meta/proto/landmark.hpp
  plugins/svgtools/include/detray/plugins/svgtools/meta/proto/trajectory.hpp
  plugins/svgtools/include/detray/plugins/svgtools/styling/styling.hpp
  tests/unit_tests/svgtools/masks.cpp
  tests/validation/include/detray/validation/detector_helix_scan.hpp
  tests/validation/include/detray/validation/detector_ray_scan.hpp
  tests/validation/include/detray/validation/helix_navigation.hpp
  tests/validation/include/detray/validation/straight_line_navigation.hpp
  tests/validation/src/detector_display.cpp
Labels: enhancement, refactor, priority: low

#603 feat: grid search
  core/include/detray/definitions/indexing.hpp
  core/include/detray/surface_finders/grid/axis.hpp
  core/include/detray/surface_finders/grid/detail/axis_binning.hpp
  core/include/detray/surface_finders/grid/detail/axis_bounds.hpp
  core/include/detray/surface_finders/grid/detail/axis_helpers.hpp
  core/include/detray/surface_finders/grid/detail/bin_view.hpp
  core/include/detray/surface_finders/grid/detail/serializer_impl.hpp
  core/include/detray/surface_finders/grid/grid.hpp
  core/include/detray/tools/bin_association.hpp
  core/include/detray/utils/ranges.hpp
  core/include/detray/utils/ranges/cartesian_product.hpp
  core/include/detray/utils/ranges/iota.hpp
  core/include/detray/utils/ranges/join.hpp
  core/include/detray/utils/ranges/pick.hpp
  core/include/detray/utils/ranges/static_join.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/volume.hpp
  tests/unit_tests/core/utils_ranges.cpp
  tests/unit_tests/cpu/grid_axis.cpp
  tests/unit_tests/cpu/grid_grid.cpp
  tests/unit_tests/cpu/grid_grid_collection.cpp
  tests/unit_tests/cpu/grid_serializer.cpp
  tests/unit_tests/device/cuda/utils_ranges_cuda.cpp
  tests/unit_tests/device/cuda/utils_ranges_cuda_kernel.cu
  tests/unit_tests/device/cuda/utils_ranges_cuda_kernel.hpp
  tests/validation/src/detector_display.cpp
Labels: enhancement, priority: high
