Repository acts-project/detray, pull requests merged in 2023-03, with the labels that each got.

#394 ref: generalize telescope to switch module shape
  core/include/detray/masks/masks.hpp
  tests/common/include/tests/common/check_simulation.inl
  tests/common/include/tests/common/line_stepper.inl
  tests/common/include/tests/common/material_interaction.inl
  tests/common/include/tests/common/test_telescope_detector.inl
  tests/common/include/tests/common/tools_guided_navigator.inl
  utils/include/detray/detectors/create_telescope_detector.hpp
  utils/include/detray/detectors/detector_metadata.hpp
Labels: enhancement, refactor, priority: medium

#395 feat: axis aligned bounding boxes
  core/CMakeLists.txt
  core/include/detray/coordinates/cylindrical3.hpp
  core/include/detray/intersection/bounding_box/cuboid_intersector.hpp
  core/include/detray/masks/annulus2D.hpp
  core/include/detray/masks/cuboid3D.hpp
  core/include/detray/masks/cylinder2D.hpp
  core/include/detray/masks/cylinder3D.hpp
  core/include/detray/masks/line.hpp
  core/include/detray/masks/masks.hpp
  core/include/detray/masks/rectangle2D.hpp
  core/include/detray/masks/ring2D.hpp
  core/include/detray/masks/single3D.hpp
  core/include/detray/masks/trapezoid2D.hpp
  core/include/detray/masks/unbounded.hpp
  core/include/detray/masks/unmasked.hpp
  core/include/detray/propagator/navigator.hpp
  core/include/detray/tools/bounding_volume.hpp
  core/include/detray/tools/grid_factory.hpp
  tests/common/include/tests/common/grid_grid.inl
  tests/common/include/tests/common/masks_annulus2D.inl
  tests/common/include/tests/common/masks_cylinder.inl
  tests/common/include/tests/common/masks_line.inl
  tests/common/include/tests/common/masks_rectangle2D.inl
  tests/common/include/tests/common/masks_ring2D.inl
  tests/common/include/tests/common/masks_single3D.inl
  tests/common/include/tests/common/masks_trapezoid2D.inl
  tests/common/include/tests/common/masks_unbounded.inl
  tests/common/include/tests/common/masks_unmasked.inl
  tests/common/include/tests/common/path_correction.inl
  tests/common/include/tests/common/tools_bounding_volume.inl
  tests/common/include/tests/common/tools_cuboid_intersector.inl
  tests/unit_tests/cpu/array/CMakeLists.txt
  tests/unit_tests/cpu/array/array_bounding_volume.cpp
  tests/unit_tests/cpu/array/array_cuboid_intersector.cpp
  tests/unit_tests/cpu/eigen/CMakeLists.txt
  tests/unit_tests/cpu/eigen/eigen_bounding_volume.cpp
  tests/unit_tests/cpu/eigen/eigen_cuboid_intersector.cpp
  tests/unit_tests/cpu/smatrix/CMakeLists.txt
  tests/unit_tests/cpu/smatrix/smatrix_bounding_volume.cpp
  tests/unit_tests/cpu/smatrix/smatrix_cuboid_intersector.cpp
  tests/unit_tests/cpu/vc/CMakeLists.txt
  tests/unit_tests/cpu/vc/vc_array_bounding_volume.cpp
  tests/unit_tests/cpu/vc/vc_array_cuboid_intersector.cpp
  tests/unit_tests/device/cuda/sf_finders_grid_cuda_kernel.hpp
Labels: enhancement, priority: medium

#396 ref: add world portals to telescope detector
  core/include/detray/core/detail/single_store.hpp
  core/include/detray/definitions/detail/algorithms.hpp
  core/include/detray/geometry/detector_volume.hpp
  core/include/detray/geometry/surface.hpp
  core/include/detray/geometry/volume_graph.hpp
  core/include/detray/intersection/detail/trajectories.hpp
  core/include/detray/intersection/intersection.hpp
  core/include/detray/masks/unbounded.hpp
  core/include/detray/tools/bounding_volume.hpp
  core/include/detray/tools/surface_factory_interface.hpp
  core/include/detray/utils/quadratic_equation.hpp
  core/include/detray/utils/ranges.hpp
  core/include/detray/utils/ranges/detail/iterator_functions.hpp
  core/include/detray/utils/ranges/empty.hpp
  core/include/detray/utils/ranges/enumerate.hpp
  core/include/detray/utils/ranges/iota.hpp
  core/include/detray/utils/ranges/join.hpp
  core/include/detray/utils/ranges/pick.hpp
  core/include/detray/utils/ranges/ranges.hpp
  core/include/detray/utils/ranges/single.hpp
  core/include/detray/utils/ranges/subrange.hpp
  core/include/detray/utils/tuple_helpers.hpp
  io/csv/include/detray/io/csv_io_types.hpp
  plugins/algebra/array/include/detray/plugins/algebra/array_definitions.hpp
  plugins/algebra/eigen/include/detray/plugins/algebra/eigen_definitions.hpp
  plugins/algebra/smatrix/include/detray/plugins/algebra/smatrix_definitions.hpp
  plugins/algebra/vc/include/detray/plugins/algebra/vc_array_definitions.hpp
  tests/common/include/tests/common/check_geometry_scan.inl
  tests/common/include/tests/common/check_simulation.inl
  tests/common/include/tests/common/line_stepper.inl
  tests/common/include/tests/common/masks_unbounded.inl
  tests/common/include/tests/common/material_interaction.inl
  tests/common/include/tests/common/tools/hash_tree.hpp
  tests/common/include/tests/common/tools/ray_scan_utils.hpp
  tests/common/include/tests/common/tools/read_geometry.hpp
  tests/common/include/tests/common/tools_bounding_volume.inl
  tests/common/include/tests/common/tools_guided_navigator.inl
  tests/common/include/tests/common/tools_track_generators.inl
  tests/unit_tests/device/cuda/detector_cuda_kernel.hpp
  tests/unit_tests/device/cuda/grids_grid2_cuda_kernel.hpp
  tests/unit_tests/device/cuda/mask_store_cuda_kernel.hpp
  tests/unit_tests/device/cuda/sf_finders_grid_cuda_kernel.hpp
  tests/unit_tests/device/cuda/transform_store_cuda_kernel.hpp
  utils/include/detray/detectors/create_telescope_detector.hpp
  utils/include/detray/detectors/detector_metadata.hpp
Labels: enhancement, refactor, priority: medium

#397 ref: pathcorrection unittest runs on telescope detector
  core/include/detray/intersection/cylinder_intersector.hpp
  core/include/detray/propagator/actors/aborters.hpp
  core/include/detray/propagator/rk_stepper.hpp
  tests/common/include/tests/common/path_correction.inl
  tests/common/include/tests/common/tools/inspectors.hpp
  tests/common/include/tests/common/tools_guided_navigator.inl
  utils/include/detray/detectors/create_telescope_detector.hpp
Labels: bug, refactor, priority: low

#403 ref!: Add config to track generators and split the header
  tests/benchmarks/cuda/benchmark_propagator_cuda.cpp
  tests/common/include/tests/common/benchmark_intersect_all.inl
  tests/common/include/tests/common/benchmark_intersect_surfaces.inl
  tests/common/include/tests/common/check_geometry_navigation.inl
  tests/common/include/tests/common/check_geometry_scan.inl
  tests/common/include/tests/common/check_simulation.inl
  tests/common/include/tests/common/test_base/propagator_test.hpp
  tests/common/include/tests/common/tools_particle_gun.inl
  tests/common/include/tests/common/tools_propagator.inl
  tests/common/include/tests/common/tools_stepper.inl
  tests/common/include/tests/common/tools_track_generators.inl
  tests/simulation/run_simulation.cpp
  tests/unit_tests/device/cuda/navigator_cuda_kernel.hpp
  utils/CMakeLists.txt
  utils/include/detray/simulation/event_generator/random_track_generator.hpp
  utils/include/detray/simulation/event_generator/track_generators.hpp
  utils/include/detray/simulation/event_generator/uniform_track_generator.hpp
  utils/include/detray/simulation/track_generators.hpp
Labels: refactor, priority: low

#412 perf: Remove Thrust calls inside kernels
  core/include/detray/definitions/detail/algorithms.hpp
  core/include/detray/utils/sort.hpp
  tests/unit_tests/core/utils_sort.cpp
Labels: refactor

#417 feat: openMP support to CPU benchmark
  tests/benchmarks/cuda/CMakeLists.txt
  tests/benchmarks/cuda/benchmark_propagator_cuda.cpp
Labels: enhancement, priority: high

#419 CMake Export Fix, main branch (2023.03.24.)
  cmake/detray-config.cmake.in
Labels: bug, priority: high

#420 Refer to `nlohmann_json` target by namespace
  io/json/CMakeLists.txt
Labels: bug

#413 feat: Add throughput to propagation benchmarks
  tests/benchmarks/cuda/benchmark_propagator_cuda.cpp
Labels: enhancement

#423 ref: surface barcode
  core/CMakeLists.txt
  core/include/detray/core/detector.hpp
  core/include/detray/definitions/detail/bit_encoder.hpp
  core/include/detray/geometry/barcode.hpp
  core/include/detray/geometry/surface.hpp
  core/include/detray/intersection/intersection.hpp
  core/include/detray/intersection/intersection_kernel.hpp
  core/include/detray/propagator/actors/aborters.hpp
  core/include/detray/propagator/navigator.hpp
  core/include/detray/propagator/propagator.hpp
  core/include/detray/tools/volume_builder.hpp
  core/include/detray/tracks/bound_track_parameters.hpp
  tests/common/include/tests/common/check_geometry_navigation.inl
  tests/common/include/tests/common/core_detector.inl
  tests/common/include/tests/common/geometry_barcode.inl
  tests/common/include/tests/common/line_stepper.inl
  tests/common/include/tests/common/material_interaction.inl
  tests/common/include/tests/common/path_correction.inl
  tests/common/include/tests/common/test_telescope_detector.inl
  tests/common/include/tests/common/test_toy_geometry.inl
  tests/common/include/tests/common/tools/inspectors.hpp
  tests/common/include/tests/common/tools/ray_scan_utils.hpp
  tests/common/include/tests/common/tools/test_surfaces.hpp
  tests/common/include/tests/common/tools_guided_navigator.inl
  tests/common/include/tests/common/tools_navigator.inl
  tests/common/include/tests/common/tools_propagator.inl
  tests/common/include/tests/common/tools_track.inl
  tests/unit_tests/cpu/array/CMakeLists.txt
  tests/unit_tests/cpu/array/array_geometry_barcode.cpp
  tests/unit_tests/cpu/eigen/CMakeLists.txt
  tests/unit_tests/cpu/eigen/eigen_geometry_barcode.cpp
  tests/unit_tests/cpu/smatrix/CMakeLists.txt
  tests/unit_tests/cpu/smatrix/smatrix_geometry_barcode.cpp
  tests/unit_tests/cpu/vc/CMakeLists.txt
  tests/unit_tests/cpu/vc/vc_array_geometry_barcode.cpp
  utils/include/detray/simulation/event_writer.hpp
Labels: bug, refactor, priority: medium
