Repository acts-project/detray, pull requests merged in 2023-02, with the labels that each got.

#382 Update algebra-plugins to version 0.17.0
  extern/algebra-plugins/CMakeLists.txt
Labels: enhancement

#381 fix: add const specialization for is_device_view trait
  core/include/detray/core/detail/container_views.hpp
  core/include/detray/core/detail/single_store.hpp
  core/include/detray/core/detail/tuple_container.hpp
Labels: bug, refactor

#392 feat: target aborter
  core/include/detray/masks/unmasked.hpp
  core/include/detray/propagator/actors/aborters.hpp
  core/include/detray/propagator/navigator.hpp
  tests/common/include/tests/common/path_correction.inl
Labels: enhancement, priority: low

#400 Remove Problematic printf-s, main branch (2023.02.24.)
  core/include/detray/propagator/actors/aborters.hpp
  core/include/detray/propagator/rk_stepper.ipp
Labels: bug, priority: high

#398 ref: additional navigation call after random scattering
  core/include/detray/propagator/propagator.hpp
  tests/common/include/tests/common/check_simulation.inl
  utils/include/detray/simulation/random_scatterer.hpp
  utils/include/detray/simulation/simulator.hpp
Labels: bug, priority: high

#393 feat: re-introduce unbounded mask
  core/include/detray/masks/masks.hpp
  core/include/detray/masks/unbounded.hpp
  tests/common/include/tests/common/masks_unbounded.inl
  tests/common/include/tests/common/masks_unmasked.inl
  tests/common/include/tests/common/tools_planar_intersection.inl
  tests/unit_tests/cpu/array/CMakeLists.txt
  tests/unit_tests/cpu/array/array_unbounded.cpp
  tests/unit_tests/cpu/eigen/CMakeLists.txt
  tests/unit_tests/cpu/eigen/eigen_unbounded.cpp
  tests/unit_tests/cpu/smatrix/CMakeLists.txt
  tests/unit_tests/cpu/smatrix/smatrix_unbounded.cpp
  tests/unit_tests/cpu/vc/CMakeLists.txt
  tests/unit_tests/cpu/vc/vc_array_unbounded.cpp
  utils/include/detray/detectors/detector_metadata.hpp
Labels: enhancement, priority: low
