Repository acts-project/detray, pull requests merged in 2023-07, with the labels that each got.

#507 Add concurrency group for CI jobs
  .github/workflows/builds.yml
  .github/workflows/checks.yml
Labels: enhancement, priority: low

#511 ref: change names of json entries
  io/include/detray/io/json/json_geometry_io.hpp
  io/include/detray/io/json/json_material_io.hpp
Labels: refactor, priority: medium

#500 ref: surface interface in navigation state
  core/include/detray/geometry/surface.hpp
  core/include/detray/intersection/concentric_cylinder_intersector.hpp
  core/include/detray/intersection/cylinder_intersector.hpp
  core/include/detray/intersection/cylinder_portal_intersector.hpp
  core/include/detray/intersection/intersection.hpp
  core/include/detray/intersection/intersection_kernel.hpp
  core/include/detray/intersection/line_intersector.hpp
  core/include/detray/intersection/plane_intersector.hpp
  core/include/detray/propagator/actors/aborters.hpp
  core/include/detray/propagator/actors/parameter_resetter.hpp
  core/include/detray/propagator/actors/parameter_transporter.hpp
  core/include/detray/propagator/actors/pointwise_material_interactor.hpp
  core/include/detray/propagator/navigator.hpp
  core/include/detray/utils/inspectors.hpp
  tests/common/include/tests/common/tools/intersectors/helix_cylinder_intersector.hpp
  tests/common/include/tests/common/tools/intersectors/helix_line_intersector.hpp
  tests/common/include/tests/common/tools/intersectors/helix_plane_intersector.hpp
  tests/common/include/tests/common/tools/particle_gun.hpp
  tests/common/include/tests/common/tools/ray_scan_utils.hpp
  tests/unit_tests/cpu/check_geometry_navigation.cpp
  tests/unit_tests/cpu/tools_guided_navigator.cpp
  tests/unit_tests/cpu/tools_intersection_kernel.cpp
  tests/unit_tests/cpu/tools_navigator.cpp
  utils/include/detray/simulation/event_writer.hpp
  utils/include/detray/simulation/random_scatterer.hpp
Labels: refactor, priority: low

#503 ref: telescope detector config
  core/include/detray/intersection/detail/trajectories.hpp
  tests/unit_tests/cpu/check_geometry_scan.cpp
  tests/unit_tests/cpu/check_simulation.cpp
  tests/unit_tests/cpu/line_stepper.cpp
  tests/unit_tests/cpu/material_interaction.cpp
  tests/unit_tests/cpu/test_telescope_detector.cpp
  tests/unit_tests/cpu/tools_guided_navigator.cpp
  tests/unit_tests/io/io_json_detector_writer.cpp
  tutorials/src/cpu/detector/build_predefined_detectors.cpp
  utils/include/detray/detectors/create_telescope_detector.hpp
Labels: refactor, priority: low

#505 ref: remove intersection from material interaction interfaces
  core/include/detray/materials/interaction.hpp
  core/include/detray/materials/material_rod.hpp
  core/include/detray/materials/material_slab.hpp
  core/include/detray/propagator/actors/parameter_resetter.hpp
  core/include/detray/propagator/actors/pointwise_material_interactor.hpp
  core/include/detray/tracks/detail/track_helper.hpp
  tests/unit_tests/cpu/energy_loss.cpp
  tests/unit_tests/cpu/material_interaction.cpp
  tests/unit_tests/cpu/materials.cpp
  utils/include/detray/simulation/random_scatterer.hpp
Labels: refactor, priority: low

#364 feat: material builders
  core/include/detray/tools/cuboid_portal_generator.hpp
  core/include/detray/tools/grid_builder.hpp
  core/include/detray/tools/material_builder.hpp
  core/include/detray/tools/material_factory.hpp
  core/include/detray/tools/surface_factory.hpp
  core/include/detray/tools/surface_factory_interface.hpp
  core/include/detray/tools/volume_builder.hpp
  core/include/detray/tools/volume_builder_interface.hpp
  tests/unit_tests/cpu/CMakeLists.txt
  tests/unit_tests/cpu/grid_grid_builder.cpp
  tests/unit_tests/cpu/tools_material_builder.cpp
  tutorials/include/detray/tutorial/square_surface_generator.hpp
Labels: enhancement, priority: high

#517 feat: detector and material reader
  core/include/detray/core/detector.hpp
  core/include/detray/materials/predefined_materials.hpp
  core/include/detray/tools/detector_builder.hpp
  core/include/detray/tools/material_builder.hpp
  core/include/detray/tools/material_factory.hpp
  io/include/detray/io/common/detail/detector_components_io.hpp
  io/include/detray/io/common/detail/utils.hpp
  io/include/detray/io/common/detector_reader.hpp
  io/include/detray/io/common/geometry_reader.hpp
  io/include/detray/io/common/geometry_writer.hpp
  io/include/detray/io/common/homogeneous_material_reader.hpp
  io/include/detray/io/common/homogeneous_material_writer.hpp
  io/include/detray/io/common/io_interface.hpp
  io/include/detray/io/common/payloads.hpp
  io/include/detray/io/json/json_geometry_io.hpp
  io/include/detray/io/json/json_header_io.hpp
  io/include/detray/io/json/json_material_io.hpp
  io/include/detray/io/json/json_reader.hpp
  io/include/detray/io/json/json_serializers.hpp
  tests/common/include/tests/common/test_toy_detector.hpp
  tests/unit_tests/cpu/materials.cpp
  tests/unit_tests/io/io_json_detector_reader.cpp
  tests/unit_tests/io/io_json_payload.cpp
  tutorials/src/cpu/detector/detector_to_dot.cpp
  tutorials/src/cpu/detector/read_detector_from_file.cpp
Labels: enhancement, priority: high

#512 fix: more expressive error message for ray scan
  tests/common/include/tests/common/tools/ray_scan_utils.hpp
Labels: bug, refactor, priority: medium

#515 feat: check detector consistency
  core/include/detray/core/detail/multi_store.hpp
  core/include/detray/core/detector.hpp
  core/include/detray/definitions/geometry.hpp
  core/include/detray/definitions/indexing.hpp
  core/include/detray/geometry/detail/surface_kernels.hpp
  core/include/detray/geometry/detail/volume_descriptor.hpp
  core/include/detray/geometry/detector_volume.hpp
  core/include/detray/geometry/surface.hpp
  core/include/detray/masks/annulus2D.hpp
  core/include/detray/masks/cuboid3D.hpp
  core/include/detray/masks/cylinder2D.hpp
  core/include/detray/masks/cylinder3D.hpp
  core/include/detray/masks/line.hpp
  core/include/detray/masks/masks.hpp
  core/include/detray/masks/rectangle2D.hpp
  core/include/detray/masks/ring2D.hpp
  core/include/detray/masks/single3D.hpp
  core/include/detray/masks/trapezoid2D.hpp
  core/include/detray/masks/unbounded.hpp
  core/include/detray/masks/unmasked.hpp
  core/include/detray/surface_finders/accelerator_grid.hpp
  core/include/detray/surface_finders/grid/axis.hpp
  core/include/detray/tools/detector_builder.hpp
  core/include/detray/tools/grid_factory.hpp
  core/include/detray/utils/consistency_checker.hpp
  core/include/detray/utils/type_traits.hpp
  io/include/detray/io/common/detector_reader.hpp
  io/include/detray/io/common/geometry_reader.hpp
  io/include/detray/io/common/geometry_writer.hpp
  io/include/detray/io/common/grid_writer.hpp
  tests/CMakeLists.txt
  tests/checks/CMakeLists.txt
  tests/checks/include/detray/checks/detector_consistency.hpp
  tests/checks/src/CMakeLists.txt
  tests/checks/src/checks_main.cpp
  tests/common/include/tests/common/test_base/fixture_base.hpp
  tests/common/include/tests/common/test_toy_detector.hpp
  tests/common/include/tests/common/tools/intersectors/helix_intersection_kernel.hpp
  tests/common/include/tests/common/tools/intersectors/helix_line_intersector.hpp
  tests/common/include/tests/common/tools/intersectors/helix_plane_intersector.hpp
  tests/unit_tests/cpu/check_geometry_linking.cpp
  tests/unit_tests/cpu/test_telescope_detector.cpp
  tests/unit_tests/device/cuda/detector_cuda.cpp
  tests/unit_tests/device/cuda/detector_cuda_kernel.cu
  tests/unit_tests/device/cuda/detector_cuda_kernel.hpp
  tests/unit_tests/io/io_json_detector_reader.cpp
  utils/include/detray/detectors/create_toy_geometry.hpp
Labels: enhancement, priority: medium
