Repository acts-project/detray, pull requests merged in 2023-10, with the labels that each got.

#528 feat: grid reader
  core/include/detray/core/detail/multi_store.hpp
  core/include/detray/core/detail/single_store.hpp
  core/include/detray/definitions/grid_axis.hpp
  core/include/detray/geometry/barcode.hpp
  core/include/detray/geometry/detail/surface_descriptor.hpp
  core/include/detray/geometry/surface.hpp
  core/include/detray/masks/masks.hpp
  core/include/detray/surface_finders/brute_force_finder.hpp
  core/include/detray/surface_finders/grid/grid.hpp
  core/include/detray/surface_finders/grid/grid_collection.hpp
  core/include/detray/tools/bin_fillers.hpp
  core/include/detray/tools/bounding_volume.hpp
  core/include/detray/tools/detector_builder.hpp
  core/include/detray/tools/grid_builder.hpp
  core/include/detray/tools/grid_factory.hpp
  core/include/detray/tools/surface_factory.hpp
  core/include/detray/tools/surface_factory_interface.hpp
  core/include/detray/tools/volume_builder.hpp
  core/include/detray/utils/consistency_checker.hpp
  core/include/detray/utils/inspectors.hpp
  core/include/detray/utils/type_list.hpp
  io/include/detray/io/common/detail/detector_components_io.hpp
  io/include/detray/io/common/detector_reader.hpp
  io/include/detray/io/common/geometry_reader.hpp
  io/include/detray/io/common/geometry_writer.hpp
  io/include/detray/io/common/grid_reader.hpp
  io/include/detray/io/common/grid_writer.hpp
  io/include/detray/io/common/homogeneous_material_reader.hpp
  io/include/detray/io/common/payloads.hpp
  io/include/detray/io/json/json_geometry_io.hpp
  io/include/detray/io/json/json_grids_io.hpp
  io/include/detray/io/json/json_reader.hpp
  io/include/detray/io/json/json_writer.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/surface.hpp
  plugins/svgtools/include/detray/plugins/svgtools/utils/mask_utils.hpp
  tests/common/include/tests/common/test_toy_detector.hpp
  tests/common/include/tests/common/tools/hash_tree.hpp
  tests/unit_tests/core/CMakeLists.txt
  tests/unit_tests/core/tools_hash_tree.cpp
  tests/unit_tests/core/utils_type_list.cpp
  tests/unit_tests/cpu/grid_grid_builder.cpp
  tests/unit_tests/cpu/tools_material_builder.cpp
  tests/unit_tests/io/io_json_detector_reader.cpp
  tests/unit_tests/io/io_json_payload.cpp
  utils/include/detray/detectors/create_toy_geometry.hpp
  utils/include/detray/detectors/create_wire_chamber.hpp
  utils/include/detray/detectors/detector_helper.hpp
  utils/include/detray/detectors/toy_metadata.hpp
Labels: bug, enhancement, refactor, priority: high

#560 feat: regular eta steps for uniform track generator
  core/include/detray/propagator/navigator.hpp
  tests/benchmarks/cpu/intersect_all.cpp
  tests/benchmarks/cpu/intersect_surfaces.cpp
  tests/benchmarks/cuda/benchmark_propagator_cuda.cpp
  tests/common/include/tests/common/test_base/propagator_test.hpp
  tests/common/include/tests/common/tools/intersectors/helix_cylinder_intersector.hpp
  tests/common/include/tests/common/tools/particle_gun.hpp
  tests/unit_tests/cpu/tools_particle_gun.cpp
  tests/unit_tests/cpu/tools_propagator.cpp
  tests/unit_tests/cpu/tools_stepper.cpp
  tests/unit_tests/cpu/tools_track_generators.cpp
  tests/unit_tests/device/cuda/navigator_cuda.cpp
  tests/unit_tests/svgtools/intersections.cpp
  tests/validation/include/detray/validation/detail/navigation_check_helper.hpp
  tests/validation/src/toy_detector_validation.cpp
  tests/validation/src/wire_chamber_validation.cpp
  tutorials/src/cpu/detector/detector_ray_scan.cpp
  tutorials/src/cpu/propagation/navigation_inspection.cpp
  tutorials/src/device/cuda/propagation.cpp
  utils/include/detray/simulation/event_generator/random_track_generator.hpp
  utils/include/detray/simulation/event_generator/uniform_track_generator.hpp
Labels: bug, enhancement, refactor, priority: high

#556 ref: Simplify surface factories and add unique payload link
  core/include/detray/surface_finders/brute_force_finder.hpp
  core/include/detray/tools/cuboid_portal_generator.hpp
  core/include/detray/tools/detector_builder.hpp
  core/include/detray/tools/material_builder.hpp
  core/include/detray/tools/material_factory.hpp
  core/include/detray/tools/surface_factory.hpp
  core/include/detray/tools/surface_factory_interface.hpp
  core/include/detray/tools/volume_builder.hpp
  core/include/detray/tools/volume_builder_interface.hpp
  core/include/detray/utils/type_registry.hpp
  io/include/detray/io/common/detail/utils.hpp
  io/include/detray/io/common/detector_reader.hpp
  io/include/detray/io/common/detector_writer.hpp
  io/include/detray/io/common/geometry_reader.hpp
  io/include/detray/io/common/homogeneous_material_reader.hpp
  io/include/detray/io/common/homogeneous_material_writer.hpp
  io/include/detray/io/common/payloads.hpp
  io/include/detray/io/json/json_material_io.hpp
  io/include/detray/io/json/json_reader.hpp
  tests/unit_tests/cpu/core_detector.cpp
  tests/unit_tests/cpu/grid_grid_builder.cpp
  tests/unit_tests/cpu/tools_material_builder.cpp
  tests/unit_tests/io/io_json_detector_reader.cpp
  tests/unit_tests/io/io_json_payload.cpp
  tutorials/include/detray/tutorial/square_surface_generator.hpp
  tutorials/src/cpu/detector/do_it_yourself_detector.cpp
  tutorials/src/cpu/detector/read_detector_from_file.cpp
  tutorials/src/cpu/detector/track_geometry_changes.cpp
  utils/include/detray/detectors/create_telescope_detector.hpp
Labels: bug, refactor, priority: medium

#561 feat: material scanner
  core/include/detray/materials/interaction.hpp
  core/include/detray/materials/material_rod.hpp
  core/include/detray/materials/material_slab.hpp
  tests/validation/CMakeLists.txt
  tests/validation/include/detray/validation/detector_material_scan.hpp
  tests/validation/python/plot_material_scan.py
  tests/validation/python/pyplot_factory.py
  tests/validation/python/run_material_validation.py
  tests/validation/src/CMakeLists.txt
  tests/validation/src/material_validation.cpp
Labels: enhancement, priority: high

#563 fix: asserts in detector building
  tests/unit_tests/cpu/core_detector.cpp
  tests/unit_tests/cpu/tools_material_builder.cpp
Labels: bug, priority: low

#568 fix: warnings in propagation tutorial and switch tutorial to inhomogeneous field
  tutorials/CMakeLists.txt
  tutorials/src/device/cuda/CMakeLists.txt
  tutorials/src/device/cuda/detector_construction.cpp
  tutorials/src/device/cuda/propagation.cpp
  tutorials/src/device/cuda/propagation.hpp
  tutorials/src/device/cuda/propagation_kernel.cu
  utils/include/detray/detectors/bfield.hpp
Labels: bug, refactor, priority: low

#578 feat: json schemas for data files
  core/include/detray/geometry/surface.hpp
  core/include/detray/utils/consistency_checker.hpp
  io/include/detray/io/common/payloads.hpp
  io/include/detray/io/json/json_geometry_io.hpp
  tests/validation/python/json_schemas/geometry.py
  tests/validation/python/json_schemas/homogeneous_material.py
  tests/validation/python/json_schemas/surface_grids.py
  tests/validation/python/run_file_checker.py
Labels: enhancement

#571 feat: integrate svgtools
  core/include/detray/tools/generators.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/landmark.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/volume.hpp
  plugins/svgtools/include/detray/plugins/svgtools/illustrator.hpp
  plugins/svgtools/include/detray/plugins/svgtools/styling/styling.hpp
  plugins/svgtools/include/detray/plugins/svgtools/writer.hpp
  tests/unit_tests/svgtools/detectors.cpp
  tests/unit_tests/svgtools/grids.cpp
  tests/unit_tests/svgtools/groups.cpp
  tests/unit_tests/svgtools/intersections.cpp
  tests/unit_tests/svgtools/landmarks.cpp
  tests/unit_tests/svgtools/masks.cpp
  tests/unit_tests/svgtools/surfaces.cpp
  tests/unit_tests/svgtools/trajectories.cpp
  tests/unit_tests/svgtools/volumes.cpp
  tests/unit_tests/svgtools/web.cpp
  tests/validation/CMakeLists.txt
  tests/validation/python/run_ray_scan_validation.py
  tests/validation/src/CMakeLists.txt
  tests/validation/src/detector_display.cpp
Labels: enhancement, priority: medium

#579 ref: Cleanup in the python directories
  .gitignore
  tests/validation/python/file_checker.py
  tests/validation/python/material_validation.py
  tests/validation/python/plotting/__init__.py
  tests/validation/python/plotting/plot_helpers.py
  tests/validation/python/plotting/pyplot_factory.py
  tests/validation/python/ray_scan_validation.py
  tests/validation/python/validation/__init__.py
  tests/validation/python/validation/json_schema/__init__.py
  tests/validation/python/validation/json_schema/geometry.py
  tests/validation/python/validation/json_schema/homogeneous_material.py
  tests/validation/python/validation/json_schema/surface_grids.py
  tests/validation/python/validation/plot_material_scan.py
  tests/validation/python/validation/plot_ray_scan.py
Labels: refactor, priority: low

#572 ref: Move the vertexing to the mask and add proto surface conversion for straw surfaces
  core/include/detray/geometry/detail/surface_kernels.hpp
  core/include/detray/geometry/surface.hpp
  core/include/detray/masks/annulus2D.hpp
  core/include/detray/masks/cuboid3D.hpp
  core/include/detray/masks/cylinder2D.hpp
  core/include/detray/masks/cylinder3D.hpp
  core/include/detray/masks/detail/vertexing.hpp
  core/include/detray/masks/line.hpp
  core/include/detray/masks/masks.hpp
  core/include/detray/masks/rectangle2D.hpp
  core/include/detray/masks/ring2D.hpp
  core/include/detray/masks/single3D.hpp
  core/include/detray/masks/trapezoid2D.hpp
  core/include/detray/masks/unbounded.hpp
  core/include/detray/masks/unmasked.hpp
  core/include/detray/tools/bin_association.hpp
  core/include/detray/tools/generators.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/surface.hpp
  plugins/svgtools/include/detray/plugins/svgtools/utils/mask_utils.hpp
Labels: enhancement, refactor, priority: low

#562 ref: use detector builder for telescope detector
  core/include/detray/surface_finders/brute_force_finder.hpp
  core/include/detray/tools/detector_builder.hpp
  core/include/detray/tools/material_factory.hpp
  core/include/detray/tools/telescope_generator.hpp
  tests/unit_tests/cpu/material_interaction.cpp
  tests/unit_tests/io/io_json_detector_reader.cpp
  utils/include/detray/detectors/create_telescope_detector.hpp
  utils/include/detray/detectors/telescope_metadata.hpp
Labels: refactor, priority: low

#580 feat: Generate detector files
  core/include/detray/intersection/detail/trajectories.hpp
  io/include/detray/io/common/detail/detector_components_io.hpp
  io/include/detray/io/common/detail/utils.hpp
  io/include/detray/io/common/detector_writer.hpp
  io/include/detray/io/common/io_interface.hpp
  io/include/detray/io/json/json_writer.hpp
  tests/CMakeLists.txt
  tests/detectors/CMakeLists.txt
  tests/detectors/src/CMakeLists.txt
  tests/detectors/src/generate_telescope_detector.cpp
  tests/detectors/src/generate_toy_detector.cpp
  tests/detectors/src/generate_wire_chamber.cpp
  tests/unit_tests/io/io_json_detector_writer.cpp
  utils/include/detray/detectors/create_telescope_detector.hpp
Labels: enhancement

#573 feat: Display svg as debug info in validation
  plugins/svgtools/include/detray/plugins/svgtools/conversion/intersection.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/intersection_record.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/landmark.hpp
  plugins/svgtools/include/detray/plugins/svgtools/illustrator.hpp
  plugins/svgtools/include/detray/plugins/svgtools/meta/display/geometry.hpp
  plugins/svgtools/include/detray/plugins/svgtools/meta/proto/intersection_record.hpp
  plugins/svgtools/include/detray/plugins/svgtools/styling/styling.hpp
  plugins/svgtools/include/detray/plugins/svgtools/utils/intersection_utils.hpp
  tests/common/include/tests/common/tools/ray_scan_utils.hpp
  tests/unit_tests/svgtools/intersections.cpp
  tests/unit_tests/svgtools/trajectories.cpp
  tests/unit_tests/svgtools/web.cpp
  tests/validation/CMakeLists.txt
  tests/validation/include/detray/validation/detail/svg_display.hpp
  tests/validation/include/detray/validation/detector_helix_scan.hpp
  tests/validation/include/detray/validation/detector_ray_scan.hpp
  tests/validation/include/detray/validation/helix_navigation.hpp
  tests/validation/include/detray/validation/straight_line_navigation.hpp
  tutorials/src/cpu/detector/detector_ray_scan.cpp
Labels: enhancement, priority: low

#586 Test Fix(es), main branch (2023.10.31.)
  tests/unit_tests/io/CMakeLists.txt
Labels: bug, priority: high

#585 Thrust Warning Suppression, main branch (2023.10.30.)
  extern/thrust/CMakeLists.txt
Labels: bug
