Repository acts-project/detray, pull requests merged in 2024-11, with the labels that each got.

#871 Remove unneeded state from Runge-Kutta stepper
  core/include/detray/propagator/rk_stepper.hpp
  core/include/detray/propagator/rk_stepper.ipp
  tests/include/detray/test/utils/inspectors.hpp
Labels: refactor

#876 feat: add python formatting as a CI job
  .github/workflows/checks.yml
  tests/tools/python/file_checker.py
  tests/tools/python/impl/__init__.py
  tests/tools/python/impl/plot_material_scan.py
  tests/tools/python/impl/plot_navigation_validation.py
  tests/tools/python/impl/plot_ray_scan.py
  tests/tools/python/impl/plot_track_params.py
  tests/tools/python/json_schema/__init__.py
  tests/tools/python/json_schema/geometry.py
  tests/tools/python/json_schema/homogeneous_material.py
  tests/tools/python/json_schema/material_maps.py
  tests/tools/python/json_schema/surface_grids.py
  tests/tools/python/material_validation.py
  tests/tools/python/navigation_validation.py
  tests/tools/python/options/__init__.py
  tests/tools/python/options/common_options.py
  tests/tools/python/options/detector_io_options.py
  tests/tools/python/options/plotting_options.py
  tests/tools/python/options/propagation_options.py
  tests/tools/python/options/track_generator_options.py
  tests/tools/python/plotting/__init__.py
  tests/tools/python/plotting/plot_helpers.py
  tests/tools/python/plotting/pyplot_factory.py
Labels: enhancement, priority: low

#882 GCC 13.1 Fix, main branch (2024.11.08.)
  core/include/detray/navigation/navigator.hpp
Labels: bug

#877 ref: Allow empty states in actor chain and construct state tuple
  core/include/detray/propagator/actor_chain.hpp
  core/include/detray/propagator/actors/parameter_resetter.hpp
  core/include/detray/propagator/actors/parameter_transporter.hpp
  core/include/detray/propagator/base_actor.hpp
Labels: refactor, priority: low

#879 ref: Remove more state data from the steppers and streamline the parameter resetter
  core/include/detray/navigation/policies.hpp
  core/include/detray/propagator/actor_chain.hpp
  core/include/detray/propagator/actors/aborters.hpp
  core/include/detray/propagator/actors/parameter_resetter.hpp
  core/include/detray/propagator/actors/parameter_transporter.hpp
  core/include/detray/propagator/actors/pointwise_material_interactor.hpp
  core/include/detray/propagator/base_stepper.hpp
  core/include/detray/propagator/line_stepper.hpp
  core/include/detray/propagator/propagator.hpp
  core/include/detray/propagator/rk_stepper.hpp
  core/include/detray/propagator/rk_stepper.ipp
  tests/integration_tests/cpu/material/material_interaction.cpp
  tests/integration_tests/cpu/propagator/jacobian_validation.cpp
  tests/integration_tests/cpu/propagator/propagator.cpp
  tests/unit_tests/cpu/propagator/rk_stepper.cpp
Labels: refactor, priority: medium

#890 VecMem Update, main branch (2024.11.29.)
  core/include/detray/core/detail/container_buffers.hpp
  extern/vecmem/CMakeLists.txt
  tests/include/detray/test/device/cuda/material_validation.hpp
  tests/include/detray/test/device/cuda/navigation_validation.hpp
  tests/integration_tests/device/cuda/propagator_cuda_kernel.hpp
  tests/integration_tests/device/sycl/propagator_sycl_kernel.hpp
  tests/unit_tests/device/cuda/grids_grid2_cuda.cpp
  tests/unit_tests/device/cuda/mask_store_cuda.cpp
  tests/unit_tests/device/cuda/navigator_cuda.cpp
  tests/unit_tests/device/cuda/utils_ranges_cuda.cpp
Labels: priority: high

#892 Project Version Update, main branch (2024.11.29.)
  CMakeLists.txt
Labels: priority: high
