Repository acts-project/detray, pull requests merged in 2024-09, with the labels that each got.

#798 ref: fixed window navigaiton
  core/include/detray/core/detail/indexing.hpp
  core/include/detray/definitions/detail/algorithms.hpp
  core/include/detray/geometry/detail/surface_descriptor.hpp
  core/include/detray/geometry/tracking_surface.hpp
  core/include/detray/geometry/tracking_volume.hpp
  core/include/detray/navigation/intersection/helix_cylinder_intersector.hpp
  core/include/detray/navigation/intersection/helix_line_intersector.hpp
  core/include/detray/navigation/intersection/helix_plane_intersector.hpp
  core/include/detray/navigation/intersection/intersection.hpp
  core/include/detray/navigation/intersection_kernel.hpp
  core/include/detray/navigation/navigator.hpp
  core/include/detray/navigation/policies.hpp
  core/include/detray/propagator/line_stepper.hpp
  core/include/detray/propagator/propagator.hpp
  core/include/detray/propagator/rk_stepper.hpp
  core/include/detray/propagator/rk_stepper.ipp
  core/include/detray/utils/inspectors.hpp
  tests/benchmarks/cpu/benchmark_propagator.cpp
  tests/benchmarks/cuda/benchmark_propagator_cuda.cpp
  tests/benchmarks/cuda/benchmark_propagator_cuda_kernel.cu
  tests/benchmarks/cuda/benchmark_propagator_cuda_kernel.hpp
  tests/include/detray/test/common/utils/navigation_validation_utils.hpp
  tests/include/detray/test/device/cuda/material_validation.cu
  tests/include/detray/test/device/cuda/material_validation.hpp
  tests/include/detray/test/device/cuda/navigation_validation.cu
  tests/include/detray/test/device/cuda/navigation_validation.hpp
  tests/include/detray/test/device/propagator_test.hpp
  tests/integration_tests/cpu/propagator/guided_navigator.cpp
  tests/integration_tests/cpu/propagator/propagator.cpp
  tests/integration_tests/device/cuda/propagator_cuda.cpp
  tests/integration_tests/device/cuda/propagator_cuda_kernel.cu
  tests/integration_tests/device/cuda/propagator_cuda_kernel.hpp
  tests/integration_tests/device/sycl/propagator.sycl
  tests/integration_tests/device/sycl/propagator_kernel.sycl
  tests/integration_tests/device/sycl/propagator_sycl_kernel.hpp
  tests/unit_tests/cpu/builders/detector_builder.cpp
  tests/unit_tests/cpu/detectors/telescope_detector.cpp
  tests/unit_tests/cpu/geometry/tracking_surface.cpp
  tests/unit_tests/cpu/geometry/tracking_volume.cpp
  tests/unit_tests/cpu/navigation/intersection/intersection_kernel.cpp
  tests/unit_tests/cpu/navigation/navigator.cpp
  tests/unit_tests/cpu/propagator/rk_stepper.cpp
  tests/unit_tests/device/cuda/navigator_cuda.cpp
  tests/unit_tests/device/cuda/navigator_cuda_kernel.cu
  tests/unit_tests/device/cuda/navigator_cuda_kernel.hpp
  tutorials/src/cpu/propagation/navigation_inspection.cpp
  tutorials/src/device/cuda/propagation.cpp
  tutorials/src/device/cuda/propagation.hpp
  tutorials/src/device/cuda/propagation_kernel.cu
  utils/include/detray/detectors/build_toy_detector.hpp
  utils/include/detray/simulation/random_scatterer.hpp
Labels: refactor, priority: high

#806 ref: Record the material steps in the material tracer
  tests/include/detray/test/common/utils/material_validation_utils.hpp
  tests/include/detray/test/common/utils/navigation_validation_utils.hpp
  tests/include/detray/test/common/utils/step_tracer.hpp
  tests/include/detray/test/cpu/material_validation.hpp
  tests/include/detray/test/cpu/navigation_validation.hpp
  tests/include/detray/test/device/cuda/material_validation.cu
  tests/include/detray/test/device/cuda/material_validation.hpp
  tests/include/detray/test/device/cuda/navigation_validation.cu
  tests/include/detray/test/device/cuda/navigation_validation.hpp
Labels: enhancement, refactor

#816 ref: Cmake fixes for traccc
  CMakeLists.txt
  detectors/CMakeLists.txt
  tests/CMakeLists.txt
Labels: bug, priority: high

#814 Add a few new navigator assertions
  core/include/detray/navigation/navigator.hpp
Labels: enhancement

#815 Ignore some bfield gradient terms in RKN Jacobian calculation
  core/include/detray/propagator/rk_stepper.ipp
Labels: optimization

#819 fix: navigation assertion
  CMakeLists.txt
  core/include/detray/navigation/navigator.hpp
Labels: bug, priority: high

#818 ref: Switch off non-esential components in CI builds
  .github/workflows/builds.yml
  .gitlab-ci.yml
  CMakeLists.txt
  extern/algebra-plugins/CMakeLists.txt
  tests/benchmarks/CMakeLists.txt
  tests/integration_tests/CMakeLists.txt
  tests/scripts/analyze_benchmarks.py
  tests/scripts/run_benchmarks.sh
  tests/tools/CMakeLists.txt
  tests/tools/src/CMakeLists.txt
  tests/tools/src/cpu/CMakeLists.txt
  tests/tools/src/cuda/CMakeLists.txt
  tests/unit_tests/CMakeLists.txt
  tutorials/src/CMakeLists.txt
  tutorials/src/cpu/CMakeLists.txt
  tutorials/src/device/cuda/CMakeLists.txt
Labels: refactor, priority: low, optimization

#822 Calculate the field gradients only at three points
  core/include/detray/propagator/rk_stepper.ipp
Labels: optimization

#821 ref: speedup device CI builds
  .gitlab-ci.yml
Labels: optimization

#828 fix: Remove compiler/linker warnings
  core/include/detray/builders/grid_builder.hpp
  core/include/detray/builders/grid_factory.hpp
  core/include/detray/geometry/mask.hpp
  core/include/detray/utils/curvilinear_frame.hpp
  tests/include/detray/test/utils/prefill_detector.hpp
  tests/unit_tests/cpu/core/mask_store.cpp
  tests/unit_tests/cpu/navigation/intersection/intersection_kernel.cpp
  tests/unit_tests/device/cuda/mask_store_cuda.cpp
  tests/unit_tests/svgtools/masks.cpp
Labels: bug, refactor, priority: high

#817 Add CMake prefix for benchmark builds
  .github/workflows/builds.yml
  CMakePresets.json
Labels: enhancement, priority: low

#808 Fix several outdated Github actions
  .github/workflows/builds.yml
  .github/workflows/checks.yml
Labels: bug

#836 Update vecmem to version 1.8.0
  extern/vecmem/CMakeLists.txt
Labels: bug, priority: high

#829 CI: switch on multithreading in the CI
  .github/workflows/builds.yml
Labels: priority: low, optimization

#835 feat: Add developer cmake presets
  .github/workflows/builds.yml
  .gitlab-ci.yml
  CMakeLists.txt
  CMakePresets.json
  README.md
  tests/CMakeLists.txt
Labels: enhancement

#820 fix: Allow different track charges in navigation validation
  core/include/detray/navigation/detail/helix.hpp
  core/include/detray/navigation/detail/ray.hpp
  core/include/detray/tracks/bound_track_parameters.hpp
  core/include/detray/tracks/free_track_parameters.hpp
  io/include/detray/io/csv/track_parameters.hpp
  tests/include/detray/test/cpu/detector_scan.hpp
  tests/include/detray/test/cpu/navigation_validation.hpp
  tests/include/detray/test/device/cuda/navigation_validation.hpp
  tests/include/detray/test/utils/detector_scanner.hpp
  tests/include/detray/test/utils/inspectors.hpp
  tests/include/detray/test/utils/navigation_validation_utils.hpp
Labels: bug, refactor

#831 Improve warnings in tuple container visitor
  core/include/detray/core/detail/tuple_container.hpp
Labels: refactor, priority: low

#833 CI: Run debug unittests
  .github/workflows/builds.yml
Labels: enhancement, priority: medium
