Repository acts-project/detray, pull requests merged in 2024-08, with the labels that each got.

#786 Split CPU and CUDA propagation benchmark
  tests/benchmarks/cpu/CMakeLists.txt
  tests/benchmarks/cpu/benchmark_propagator.cpp
  tests/benchmarks/cuda/benchmark_propagator_cuda.cpp
  tests/scripts/run_benchmarks.sh
Labels: priority: high

#790 Remove the covariance matrix from the free track parameters
  core/include/detray/definitions/track_parametrization.hpp
  core/include/detray/propagator/actors/parameter_transporter.hpp
  core/include/detray/propagator/base_stepper.hpp
  core/include/detray/propagator/propagator.hpp
  core/include/detray/tracks/bound_track_parameters.hpp
  core/include/detray/tracks/detail/track_helper.hpp
  core/include/detray/tracks/free_track_parameters.hpp
  core/include/detray/utils/curvilinear_frame.hpp
  tests/integration_tests/cpu/propagator/propagator.cpp
  tests/unit_tests/cpu/CMakeLists.txt
  tests/unit_tests/cpu/tracks/bound_track_parameters.cpp
  tests/unit_tests/cpu/tracks/free_track_parameters.cpp
  tests/unit_tests/cpu/utils/curvilinear_frame.cpp
Labels: refactor, optimization

#792 ref: Remove distiction between free vector and free track parameters
  core/include/detray/geometry/detail/surface_kernels.hpp
  core/include/detray/geometry/mask.hpp
  core/include/detray/geometry/tracking_surface.hpp
  core/include/detray/navigation/detail/helix.hpp
  core/include/detray/navigation/detail/ray.hpp
  core/include/detray/navigation/intersection/bounding_box/cuboid_intersector.hpp
  core/include/detray/navigation/intersection/ray_concentric_cylinder_intersector.hpp
  core/include/detray/navigation/intersection/ray_cylinder_intersector.hpp
  core/include/detray/navigation/intersection/ray_cylinder_portal_intersector.hpp
  core/include/detray/navigation/intersection/ray_line_intersector.hpp
  core/include/detray/navigation/intersection/ray_plane_intersector.hpp
  core/include/detray/propagator/actors/parameter_resetter.hpp
  core/include/detray/propagator/actors/parameter_transporter.hpp
  core/include/detray/propagator/detail/jacobian_engine.hpp
  core/include/detray/tracks/detail/track_helper.hpp
  core/include/detray/tracks/detail/transform_track_parameters.hpp
  core/include/detray/tracks/free_track_parameters.hpp
  core/include/detray/utils/curvilinear_frame.hpp
  tests/integration_tests/cpu/propagator/covariance_transport.cpp
  tests/integration_tests/cpu/propagator/jacobian_validation.cpp
  tests/integration_tests/cpu/propagator/propagator.cpp
  tests/unit_tests/cpu/propagator/jacobian_cartesian.cpp
  tests/unit_tests/cpu/propagator/jacobian_cylindrical.cpp
  tests/unit_tests/cpu/propagator/jacobian_line.cpp
  tests/unit_tests/cpu/propagator/jacobian_polar.cpp
  tests/unit_tests/cpu/propagator/rk_stepper.cpp
  tests/unit_tests/cpu/tracks/free_track_parameters.cpp
Labels: bug, refactor, priority: low

#795 ref: Move the transform index onto the barcode
  core/include/detray/geometry/barcode.hpp
  core/include/detray/geometry/detail/surface_descriptor.hpp
  tests/benchmarks/cpu/intersect_surfaces.cpp
  tests/benchmarks/cpu/intersectors.cpp
  tests/include/detray/test/common/utils/planes_along_direction.hpp
  tests/integration_tests/cpu/propagator/guided_navigator.cpp
  tests/unit_tests/cpu/geometry/barcode.cpp
  tests/unit_tests/cpu/navigation/brute_force_finder.cpp
Labels: refactor, priority: low

#794 ref: bound track parameter interface
  core/include/detray/geometry/detail/surface_kernels.hpp
  core/include/detray/geometry/tracking_surface.hpp
  core/include/detray/propagator/actors/parameter_resetter.hpp
  core/include/detray/propagator/actors/parameter_transporter.hpp
  core/include/detray/propagator/actors/pointwise_material_interactor.hpp
  core/include/detray/propagator/base_stepper.hpp
  core/include/detray/propagator/detail/jacobian_cartesian.hpp
  core/include/detray/propagator/detail/jacobian_engine.hpp
  core/include/detray/tracks/bound_track_parameters.hpp
  core/include/detray/tracks/detail/track_helper.hpp
  core/include/detray/tracks/detail/transform_track_parameters.hpp
  core/include/detray/utils/curvilinear_frame.hpp
  tests/integration_tests/cpu/material/material_interaction.cpp
  tests/integration_tests/cpu/propagator/covariance_transport.cpp
  tests/integration_tests/cpu/propagator/jacobian_validation.cpp
  tests/integration_tests/cpu/propagator/propagator.cpp
  tests/unit_tests/cpu/propagator/covariance_transport.cpp
  tests/unit_tests/cpu/propagator/jacobian_cartesian.cpp
  tests/unit_tests/cpu/propagator/jacobian_cylindrical.cpp
  tests/unit_tests/cpu/propagator/jacobian_line.cpp
  tests/unit_tests/cpu/propagator/jacobian_polar.cpp
  tests/unit_tests/cpu/tracks/bound_track_parameters.cpp
  tests/unit_tests/cpu/utils/curvilinear_frame.cpp
  utils/include/detray/simulation/random_scatterer.hpp
Labels: refactor, priority: low
