Repository acts-project/detray, pull requests merged in 2024-07, with the labels that each got.

#764 ref: Add labels to the material svgs
  plugins/svgtools/include/detray/plugins/svgtools/styling/styling.hpp
Labels: refactor, priority: medium

#745 Add CI jobs for the C++20 standard
  .github/workflows/builds.yml
  core/include/detray/navigation/navigator.hpp
  core/include/detray/utils/inspectors.hpp
  core/include/detray/utils/statistics.hpp
  tests/benchmarks/cpu/masks.cpp
  tests/scripts/run_benchmarks.sh
  tutorials/src/cpu/detector/do_it_yourself_detector.cpp
Labels: enhancement, priority: medium

#770 ref: Remove thrust dependency
  CMakeLists.txt
  cmake/detray-config.cmake.in
  core/CMakeLists.txt
  core/include/detray/definitions/detail/algorithms.hpp
  core/include/detray/grids/populator.hpp
  core/include/detray/utils/find_bound.hpp
  core/include/detray/utils/ranges/detail/iterator_functions.hpp
  core/include/detray/utils/unit_vectors.hpp
  extern/thrust/CMakeLists.txt
  extern/thrust/README.md
  tests/unit_tests/cpu/CMakeLists.txt
  tests/unit_tests/cpu/utils/find_bounds.cpp
  tests/unit_tests/cpu/utils/unit_vectors.cpp
Labels: refactor, priority: high

#767 fix: access to material parameters from tracking surface
  core/include/detray/geometry/detail/surface_kernels.hpp
  core/include/detray/geometry/detail/volume_kernels.hpp
  core/include/detray/geometry/tracking_surface.hpp
  core/include/detray/geometry/tracking_volume.hpp
  core/include/detray/materials/material.hpp
  core/include/detray/materials/material_map.hpp
  core/include/detray/materials/material_rod.hpp
  core/include/detray/materials/material_slab.hpp
  core/include/detray/propagator/actors/pointwise_material_interactor.hpp
  core/include/detray/utils/consistency_checker.hpp
  core/include/detray/utils/type_traits.hpp
  io/include/detray/io/common/detail/type_info.hpp
  tests/include/detray/test/common/utils/material_validation_utils.hpp
  tests/unit_tests/cpu/geometry/tracking_surface.cpp
Labels: bug, refactor

#723 ref: Remove the incidence angle from the intersection
  core/include/detray/geometry/tracking_surface.hpp
  core/include/detray/navigation/intersection/helix_cylinder_intersector.hpp
  core/include/detray/navigation/intersection/helix_line_intersector.hpp
  core/include/detray/navigation/intersection/helix_plane_intersector.hpp
  core/include/detray/navigation/intersection/intersection.hpp
  core/include/detray/navigation/intersection/ray_concentric_cylinder_intersector.hpp
  core/include/detray/navigation/intersection/ray_cylinder_intersector.hpp
  core/include/detray/navigation/intersection/ray_line_intersector.hpp
  core/include/detray/navigation/intersection/ray_plane_intersector.hpp
  core/include/detray/navigation/intersection/soa/ray_cylinder_intersector.hpp
  core/include/detray/navigation/intersection/soa/ray_line_intersector.hpp
  core/include/detray/navigation/intersection/soa/ray_plane_intersector.hpp
  core/include/detray/propagator/actors/pointwise_material_interactor.hpp
  core/include/detray/utils/root_finding.hpp
  io/include/detray/io/csv/intersection2D.hpp
  tests/unit_tests/cpu/geometry/tracking_surface.cpp
  tests/unit_tests/cpu/material/materials.cpp
  tests/unit_tests/cpu/navigation/intersection/cylinder_intersector.cpp
  tests/unit_tests/cpu/navigation/intersection/helix_intersector.cpp
  tests/unit_tests/cpu/navigation/intersection/intersection2D.cpp
  tests/unit_tests/cpu/navigation/intersection/line_intersector.cpp
  tests/unit_tests/cpu/navigation/intersection/plane_intersector.cpp
  utils/include/detray/simulation/random_scatterer.hpp
Labels: refactor, priority: low

#773 Replace `math::abs` with `math::fabs` where needed
  core/include/detray/builders/cylinder_portal_generator.hpp
  core/include/detray/geometry/coordinates/line2D.hpp
  core/include/detray/navigation/detail/helix.hpp
  core/include/detray/navigation/intersection/helix_cylinder_intersector.hpp
  core/include/detray/navigation/intersection/helix_line_intersector.hpp
  core/include/detray/navigation/intersection/helix_plane_intersector.hpp
  core/include/detray/navigation/intersection/ray_concentric_cylinder_intersector.hpp
  core/include/detray/navigation/policies.hpp
  core/include/detray/propagator/line_stepper.hpp
  core/include/detray/tracks/bound_track_parameters.hpp
  core/include/detray/tracks/free_track_parameters.hpp
  core/include/detray/utils/inspectors.hpp
  core/include/detray/utils/quadratic_equation.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/surface.hpp
  tests/integration_tests/cpu/propagator/jacobian_validation.cpp
  tutorials/include/detray/tutorial/my_square2D.hpp
  utils/include/detray/detectors/factories/barrel_generator.hpp
Labels: bug

#774 Update algebra-plugins to v0.25.0
  extern/algebra-plugins/CMakeLists.txt
Labels: enhancement

#775 Update actsvg version to v0.4.45
  extern/actsvg/CMakeLists.txt
Labels: enhancement

#776 Fix a few more floating point conversion errors
  core/include/detray/grids/axis.hpp
  tests/unit_tests/cpu/navigation/intersection/helix_trajectory.cpp
  tests/unit_tests/cpu/propagator/jacobian_polar.cpp
  tests/unit_tests/cpu/utils/bounding_volume.cpp
  tests/unit_tests/cpu/utils/grids/grid_collection.cpp
Labels: bug

#777 Mark dependencies as system libraries
  extern/actsvg/CMakeLists.txt
  extern/algebra-plugins/CMakeLists.txt
  extern/benchmark/CMakeLists.txt
  extern/covfie/CMakeLists.txt
  extern/dfelibs/CMakeLists.txt
  extern/googletest/CMakeLists.txt
  extern/nlohmann_json/CMakeLists.txt
  extern/vecmem/CMakeLists.txt
Labels: enhancement

#778 fix: Update surface material selection in random scatterer
  utils/include/detray/simulation/random_scatterer.hpp
Labels: bug, priority: high

#782 Add missing eta range in SYCL propagator test
  tests/integration_tests/device/sycl/propagator.sycl
Labels: bug

#771 Raise minimum C++ version to 20
  .github/ci_setup.sh
  .github/workflows/builds.yml
  .gitlab-ci.yml
  CMakeLists.txt
  core/include/detray/navigation/detail/helix.hpp
  plugins/algebra/smatrix/include/detray/plugins/algebra/smatrix_definitions.hpp
Labels: enhancement
