Repository acts-project/detray, pull requests merged in 2024-05, with the labels that each got.

#719 fix: json file checker
  tests/tools/python/file_checker.py
Labels: bug, priority: high

#720 feat: Add material map display to svgtools
  extern/actsvg/CMakeLists.txt
  plugins/svgtools/include/detray/plugins/svgtools/conversion/grid.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/portal.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/surface.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/surface_grid.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/surface_material.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/volume.hpp
  plugins/svgtools/include/detray/plugins/svgtools/illustrator.hpp
  plugins/svgtools/include/detray/plugins/svgtools/styling/colors.hpp
  plugins/svgtools/include/detray/plugins/svgtools/styling/styling.hpp
  tests/tools/src/detector_display.cpp
  tests/unit_tests/svgtools/CMakeLists.txt
  tests/unit_tests/svgtools/grids.cpp
  tests/unit_tests/svgtools/groups.cpp
  tests/unit_tests/svgtools/material.cpp
  tests/unit_tests/svgtools/surfaces.cpp
Labels: enhancement, refactor, priority: high

#727 ref: Deduplicate navigation validation code and make it more reusable
  tests/CMakeLists.txt
  tests/include/detray/test/detail/register_checks.hpp
  tests/include/detray/test/detector_consistency.hpp
  tests/include/detray/test/detector_helix_scan.hpp
  tests/include/detray/test/detector_ray_scan.hpp
  tests/include/detray/test/detector_scan.hpp
  tests/include/detray/test/detector_scan_config.hpp
  tests/include/detray/test/helix_navigation.hpp
  tests/include/detray/test/navigation_validation.hpp
  tests/include/detray/test/navigation_validation_config.hpp
  tests/include/detray/test/straight_line_navigation.hpp
  tests/include/detray/test/utils/detector_scan_utils.hpp
  tests/include/detray/test/utils/detector_scanner.hpp
  tests/include/detray/test/utils/navigation_check_helper.hpp
  tests/include/detray/test/utils/navigation_validation_utils.hpp
  tests/integration_tests/cpu/CMakeLists.txt
  tests/integration_tests/cpu/detectors/telescope_detector_navigation.cpp
  tests/integration_tests/cpu/detectors/toy_detector_navigation.cpp
  tests/integration_tests/cpu/detectors/wire_chamber_navigation.cpp
  tests/tools/include/detray/validation/detector_material_scan.hpp
  tests/tools/src/detector_validation.cpp
  tests/unit_tests/cpu/navigation/intersection/helix_trajectory.cpp
  tests/unit_tests/cpu/simulation/detector_scanner.cpp
  tests/unit_tests/svgtools/intersections.cpp
  tests/unit_tests/svgtools/trajectories.cpp
  tests/unit_tests/svgtools/web.cpp
  tutorials/CMakeLists.txt
  tutorials/src/cpu/detector/detector_ray_scan.cpp
  tutorials/src/cpu/detector/track_geometry_changes.cpp
  tutorials/src/cpu/propagation/navigation_inspection.cpp
Labels: refactor, priority: high

#733 fix: navigation status update
  core/include/detray/navigation/navigator.hpp
Labels: bug, priority: high

#732 feat: cuda navigation validation
  core/include/detray/core/detail/container_buffers.hpp
  core/include/detray/core/detail/container_views.hpp
  core/include/detray/core/detail/single_store.hpp
  core/include/detray/core/detector.hpp
  core/include/detray/geometry/detail/volume_kernels.hpp
  core/include/detray/geometry/detector_volume.hpp
  core/include/detray/navigation/navigator.hpp
  core/include/detray/propagator/propagator.hpp
  core/include/detray/utils/inspectors.hpp
  io/include/detray/io/csv/intersection2D.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/intersection.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/volume.hpp
  plugins/svgtools/include/detray/plugins/svgtools/illustrator.hpp
  plugins/svgtools/include/detray/plugins/svgtools/meta/display/geometry.hpp
  tests/include/detray/test/detail/whiteboard.hpp
  tests/include/detray/test/detector_consistency.hpp
  tests/include/detray/test/detector_scan.hpp
  tests/include/detray/test/navigation_validation.hpp
  tests/include/detray/test/navigation_validation_config.hpp
  tests/include/detray/test/utils/detector_scan_utils.hpp
  tests/include/detray/test/utils/detector_scanner.hpp
  tests/include/detray/test/utils/navigation_validation_utils.hpp
  tests/include/detray/test/utils/svg_display.hpp
  tests/integration_tests/cpu/propagator/guided_navigator.cpp
  tests/integration_tests/device/cuda/CMakeLists.txt
  tests/integration_tests/device/cuda/navigation_validation.cu
  tests/integration_tests/device/cuda/navigation_validation.hpp
  tests/integration_tests/device/cuda/telescope_navigation_validation.cpp
  tests/integration_tests/device/cuda/toy_detector_navigation_validation.cpp
  tests/integration_tests/device/cuda/wire_chamber_navigation_validation.cpp
  tests/tools/include/detray/validation/detector_material_scan.hpp
  tests/tools/src/detector_display.cpp
  tests/tools/src/detector_validation.cpp
  tests/unit_tests/cpu/navigation/navigator.cpp
  tests/unit_tests/svgtools/intersections.cpp
  tests/unit_tests/svgtools/trajectories.cpp
  tests/unit_tests/svgtools/web.cpp
  tutorials/src/cpu/detector/detector_ray_scan.cpp
  tutorials/src/cpu/propagation/navigation_inspection.cpp
Labels: enhancement

#709 feat: Move material maps generation to factory, add material maps to new toy detector and remove old toy detector
  core/include/detray/builders/cylinder_portal_generator.hpp
  core/include/detray/builders/homogeneous_material_factory.hpp
  core/include/detray/builders/homogeneous_material_generator.hpp
  core/include/detray/builders/material_map_builder.hpp
  core/include/detray/builders/material_map_factory.hpp
  core/include/detray/builders/material_map_generator.hpp
  core/include/detray/builders/surface_factory_interface.hpp
  core/include/detray/geometry/detail/surface_kernels.hpp
  core/include/detray/geometry/surface.hpp
  tests/include/detray/test/toy_detector_test.hpp
  tests/integration_tests/io/io_json_detector_roundtrip.cpp
  tests/tools/src/generate_toy_detector.cpp
  tests/unit_tests/cpu/detectors/toy_detector.cpp
  tests/unit_tests/svgtools/material.cpp
  tests/validation/python/validation/plot_material_scan.py
  utils/include/detray/detectors/build_toy_detector.hpp
  utils/include/detray/detectors/create_toy_geometry.hpp
  utils/include/detray/detectors/create_wire_chamber.hpp
  utils/include/detray/detectors/detector_helper.hpp
Labels: enhancement, refactor, priority: high

#738 fix: navigation and make mask tolerance scaling configurable
  core/include/detray/definitions/detail/math.hpp
  core/include/detray/navigation/intersection/helix_cylinder_intersector.hpp
  core/include/detray/navigation/intersection/helix_line_intersector.hpp
  core/include/detray/navigation/intersection/helix_plane_intersector.hpp
  core/include/detray/navigation/intersection/intersection.hpp
  core/include/detray/navigation/intersection/ray_concentric_cylinder_intersector.hpp
  core/include/detray/navigation/intersection/ray_cylinder_intersector.hpp
  core/include/detray/navigation/intersection/ray_cylinder_portal_intersector.hpp
  core/include/detray/navigation/intersection/ray_line_intersector.hpp
  core/include/detray/navigation/intersection/ray_plane_intersector.hpp
  core/include/detray/navigation/intersection/soa/ray_cylinder_intersector.hpp
  core/include/detray/navigation/intersection/soa/ray_cylinder_portal_intersector.hpp
  core/include/detray/navigation/intersection/soa/ray_line_intersector.hpp
  core/include/detray/navigation/intersection/soa/ray_plane_intersector.hpp
  core/include/detray/navigation/intersection_kernel.hpp
  core/include/detray/navigation/intersector.hpp
  core/include/detray/navigation/navigation_config.hpp
  core/include/detray/navigation/navigator.hpp
  core/include/detray/utils/inspectors.hpp
  io/include/detray/io/csv/intersection2D.hpp
  io/include/detray/io/csv/track_parameters.hpp
  io/include/detray/io/utils/create_path.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/surface_grid.hpp
  tests/integration_tests/cpu/detectors/telescope_detector_navigation.cpp
  tests/tools/include/detray/options/propagation_options.hpp
  tests/unit_tests/cpu/navigation/intersection/intersection_kernel.cpp
Labels: bug, enhancement, refactor, priority: high

#746 Fix C++20 bug in axis constructor
  core/include/detray/utils/grid/detail/axis.hpp
Labels: bug, priority: medium
