Repository acts-project/detray, pull requests merged in 2024-10, with the labels that each got.

#844 Add FP64 compliance CI job
  .github/find_f64_ptx.py
  .github/workflows/builds.yml
  cmake/detray-compiler-options-cuda.cmake
  cmake/detray-functions.cmake
Labels: enhancement, priority: medium

#842 feat: ranges concepts
  core/include/detray/definitions/detail/algorithms.hpp
  core/include/detray/navigation/accelerators/brute_force_finder.hpp
  core/include/detray/utils/find_bound.hpp
  core/include/detray/utils/grid/detail/bin_storage.hpp
  core/include/detray/utils/grid/detail/bin_view.hpp
  core/include/detray/utils/ranges/cartesian_product.hpp
  core/include/detray/utils/ranges/detail/iterator_functions.hpp
  core/include/detray/utils/ranges/enumerate.hpp
  core/include/detray/utils/ranges/iota.hpp
  core/include/detray/utils/ranges/join.hpp
  core/include/detray/utils/ranges/pick.hpp
  core/include/detray/utils/ranges/ranges.hpp
  core/include/detray/utils/ranges/static_join.hpp
  core/include/detray/utils/ranges/subrange.hpp
  core/include/detray/utils/sort.hpp
  plugins/svgtools/include/detray/plugins/svgtools/illustrator.hpp
  tests/include/detray/test/utils/statistics.hpp
  tests/unit_tests/cpu/utils/grids/grid.cpp
  tests/unit_tests/cpu/utils/ranges.cpp
Labels: enhancement, refactor, priority: low

#847 Make propagate() and propagate_sync() equal
  core/include/detray/propagator/propagator.hpp
Labels: bug

#839 ref: Rename vc to vc_aos and build vc_soa plugin in CI
  .github/workflows/builds.yml
  CMakeLists.txt
  CMakePresets.json
  README.md
  cmake/detray-config.cmake.in
  core/CMakeLists.txt
  core/include/detray/definitions/detail/algebra.hpp
  extern/algebra-plugins/CMakeLists.txt
  io/CMakeLists.txt
  plugins/algebra/CMakeLists.txt
  plugins/algebra/eigen/CMakeLists.txt
  plugins/algebra/smatrix/CMakeLists.txt
  plugins/algebra/vc/CMakeLists.txt
  plugins/algebra/vc_aos/CMakeLists.txt
  plugins/algebra/vc_aos/include/detray/plugins/algebra/vc_aos_definitions.hpp
  plugins/algebra/vc_soa/CMakeLists.txt
  tests/benchmarks/cpu/CMakeLists.txt
  tests/include/detray/test/utils/types.hpp
  tests/integration_tests/cpu/CMakeLists.txt
  tests/unit_tests/cpu/CMakeLists.txt
Labels: refactor, priority: low

#843 ref: remove enable_if
  core/include/detray/builders/detail/bin_association.hpp
  core/include/detray/builders/grid_factory.hpp
  core/include/detray/core/detail/indexing.hpp
  core/include/detray/core/detail/multi_store.hpp
  core/include/detray/core/detail/single_store.hpp
  core/include/detray/core/detail/surface_lookup.hpp
  core/include/detray/core/detail/tuple_container.hpp
  core/include/detray/core/detector.hpp
  core/include/detray/definitions/detail/containers.hpp
  core/include/detray/definitions/detail/math.hpp
  core/include/detray/geometry/mask.hpp
  core/include/detray/geometry/tracking_surface.hpp
  core/include/detray/grids/axis.hpp
  core/include/detray/grids/grid2.hpp
  core/include/detray/materials/detail/material_accessor.hpp
  core/include/detray/navigation/accelerators/brute_force_finder.hpp
  core/include/detray/navigation/navigator.hpp
  core/include/detray/propagator/constrained_step.hpp
  core/include/detray/propagator/detail/jacobian_engine.hpp
  core/include/detray/utils/bit_encoder.hpp
  core/include/detray/utils/bounding_volume.hpp
  core/include/detray/utils/consistency_checker.hpp
  core/include/detray/utils/grid/detail/axis.hpp
  core/include/detray/utils/grid/detail/axis_helpers.hpp
  core/include/detray/utils/grid/detail/bin_storage.hpp
  core/include/detray/utils/grid/grid.hpp
  core/include/detray/utils/grid/grid_collection.hpp
  core/include/detray/utils/invalid_values.hpp
  core/include/detray/utils/quadratic_equation.hpp
  core/include/detray/utils/ranges/enumerate.hpp
  core/include/detray/utils/ranges/subrange.hpp
  core/include/detray/utils/tuple.hpp
  core/include/detray/utils/tuple_helpers.hpp
  io/include/detray/io/common/detail/grid_reader.hpp
  io/include/detray/io/common/detail/type_info.hpp
  io/include/detray/io/common/geometry_writer.hpp
  io/include/detray/io/frontend/detail/detector_components_reader.hpp
  io/include/detray/io/frontend/detail/detector_components_writer.hpp
  plugins/algebra/vc_soa/include/detray/plugins/algebra/vc_soa_definitions.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/grid.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/surface.hpp
  plugins/svgtools/include/detray/plugins/svgtools/utils/surface_kernels.hpp
  tests/include/detray/test/cpu/toy_detector_test.hpp
  tests/include/detray/test/utils/detector_scan_utils.hpp
  tests/include/detray/test/utils/detectors/build_telescope_detector.hpp
  tests/include/detray/test/utils/hash_tree.hpp
  tests/include/detray/test/utils/inspectors.hpp
  tests/unit_tests/cpu/propagator/actor_chain.cpp
  tests/unit_tests/device/cuda/container_cuda_kernel.hpp
  tutorials/include/detray/tutorial/detector_metadata.hpp
  tutorials/src/cpu/propagation/define_an_actor.cpp
Labels: refactor, priority: low

#848 ref: Use ranges algorithms
  core/include/detray/builders/homogeneous_material_factory.hpp
  core/include/detray/builders/material_map_factory.hpp
  core/include/detray/builders/material_map_generator.hpp
  core/include/detray/builders/volume_builder.hpp
  core/include/detray/core/detector.hpp
  core/include/detray/definitions/detail/algorithms.hpp
  core/include/detray/geometry/tracking_volume.hpp
  core/include/detray/grids/axis.hpp
  core/include/detray/grids/grid2.hpp
  core/include/detray/grids/populator.hpp
  core/include/detray/materials/detail/material_accessor.hpp
  core/include/detray/navigation/intersection/intersection.hpp
  core/include/detray/utils/grid/detail/bin_storage.hpp
  core/include/detray/utils/grid/detail/grid_bins.hpp
  core/include/detray/utils/ranges/ranges.hpp
  core/include/detray/utils/ranges/single.hpp
  core/include/detray/utils/sort.hpp
  io/include/detray/io/common/detail/grid_reader.hpp
  io/include/detray/io/common/detail/grid_writer.hpp
  io/include/detray/io/common/geometry_reader.hpp
  io/include/detray/io/common/geometry_writer.hpp
  io/include/detray/io/frontend/detail/detector_components_writer.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/grid.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/surface.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/surface_grid.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/surface_material.hpp
  plugins/svgtools/include/detray/plugins/svgtools/meta/display/tracking.hpp
  tests/benchmarks/cpu/grid.cpp
  tests/benchmarks/cpu/intersectors.cpp
  tests/include/detray/test/cpu/toy_detector_test.hpp
  tests/include/detray/test/utils/detector_scanner.hpp
  tests/include/detray/test/utils/detectors/build_telescope_detector.hpp
  tests/include/detray/test/utils/detectors/factories/barrel_generator.hpp
  tests/include/detray/test/utils/navigation_validation_utils.hpp
  tests/include/detray/test/utils/simulation/event_generator/random_track_generator.hpp
  tests/include/detray/test/utils/simulation/event_generator/uniform_track_generator.hpp
  tests/include/detray/test/utils/statistics.hpp
  tests/integration_tests/cpu/propagator/jacobian_validation.cpp
  tests/unit_tests/cpu/geometry/tracking_volume.cpp
  tests/unit_tests/cpu/navigation/intersection/intersection2D.cpp
  tests/unit_tests/cpu/simulation/landau_sampling.cpp
  tests/unit_tests/cpu/utils/grids/grid.cpp
  tests/unit_tests/cpu/utils/grids/grid_collection.cpp
  tests/unit_tests/cpu/utils/grids/populators.cpp
  tests/unit_tests/device/cuda/container_cuda.cpp
  tests/unit_tests/device/cuda/sf_finders_grid_cuda.cpp
Labels: refactor, priority: low

#834 ref: split dependency between benchmarks and svgtools and make validation utils lib
  .github/workflows/builds.yml
  CMakeLists.txt
  tests/CMakeLists.txt
  tests/include/detray/test/cpu/CMakeLists.txt
  tests/include/detray/test/cpu/detector_scan.hpp
  tests/include/detray/test/cpu/material_scan.hpp
  tests/include/detray/test/cpu/material_validation.hpp
  tests/include/detray/test/cpu/navigation_validation.hpp
  tests/include/detray/test/device/cuda/CMakeLists.txt
  tests/include/detray/test/device/cuda/material_validation.hpp
  tests/include/detray/test/device/cuda/navigation_validation.hpp
  tests/include/detray/test/device/propagator_test.hpp
  tests/include/detray/test/validation/detector_scan_utils.hpp
  tests/include/detray/test/validation/detector_scanner.hpp
  tests/include/detray/test/validation/material_validation_utils.hpp
  tests/include/detray/test/validation/navigation_validation_utils.hpp
  tests/include/detray/test/validation/step_tracer.hpp
  tests/include/detray/test/validation/svg_display.hpp
  tests/tools/python/file_checker.py
  tests/tools/python/impl/__init__.py
  tests/tools/python/impl/plot_material_scan.py
  tests/tools/python/impl/plot_navigation_validation.py
  tests/tools/python/impl/plot_ray_scan.py
  tests/tools/python/impl/plot_track_params.py
  tests/tools/python/json_schema/__init__.py
  tests/tools/python/json_schema/geometry.py
  tests/tools/python/json_schema/homogeneous_material.py
  tests/tools/python/json_schema/material_maps.py
  tests/tools/python/json_schema/surface_grids.py
  tests/tools/python/material_validation.py
  tests/tools/python/navigation_validation.py
  tests/tools/python/options/__init__.py
  tests/tools/python/options/common_options.py
  tests/tools/python/options/detector_io_options.py
  tests/tools/python/options/plotting_options.py
  tests/tools/python/options/propagation_options.py
  tests/tools/python/options/track_generator_options.py
  tests/tools/python/plotting/__init__.py
  tests/tools/python/plotting/plot_helpers.py
  tests/tools/python/plotting/pyplot_factory.py
  tests/tools/root/covariance_validation.C
  tests/tools/root/jacobian_comparison.C
  tests/tools/root/jacobian_histogram.C
  tests/tools/root/rk_tolerance_comparison.C
  tests/tools/scripts/run_jacobian_validation.sh
  tests/unit_tests/cpu/simulation/detector_scanner.cpp
  tests/unit_tests/svgtools/intersections.cpp
  tests/unit_tests/svgtools/trajectories.cpp
  tests/unit_tests/svgtools/web.cpp
  tutorials/src/cpu/CMakeLists.txt
  tutorials/src/cpu/detector/detector_ray_scan.cpp
  tutorials/src/cpu/propagation/navigation_inspection.cpp
Labels: refactor, priority: low

#853 ref: Use the detector builder for the wire chamber geometry
  core/include/detray/builders/cylinder_portal_generator.hpp
  core/include/detray/builders/grid_builder.hpp
  core/include/detray/builders/homogeneous_material_builder.hpp
  core/include/detray/builders/homogeneous_volume_material_builder.hpp
  core/include/detray/builders/material_map_builder.hpp
  core/include/detray/builders/surface_factory.hpp
  core/include/detray/builders/volume_builder.hpp
  core/include/detray/core/detail/container_buffers.hpp
  core/include/detray/core/detector.hpp
  tests/include/detray/test/utils/detectors/build_toy_detector.hpp
  tests/include/detray/test/utils/detectors/build_wire_chamber.hpp
  tests/include/detray/test/utils/detectors/create_wire_chamber.hpp
  tests/include/detray/test/utils/detectors/factories/barrel_generator.hpp
  tests/include/detray/test/utils/detectors/factories/wire_layer_generator.hpp
  tests/include/detray/test/utils/prefill_detector.hpp
  tests/integration_tests/cpu/builders/volume_builder.cpp
  tests/integration_tests/cpu/detectors/wire_chamber_navigation.cpp
  tests/integration_tests/cpu/propagator/jacobian_validation.cpp
  tests/integration_tests/device/cuda/wire_chamber_navigation_validation.cpp
  tests/integration_tests/io/io_json_detector_roundtrip.cpp
  tests/tools/include/detray/options/wire_chamber_options.hpp
  tests/tools/src/cpu/generate_wire_chamber.cpp
  tests/unit_tests/cpu/builders/volume_builder.cpp
  tests/unit_tests/cpu/core/detector.cpp
  tests/unit_tests/cpu/detectors/wire_chamber.cpp
  tests/unit_tests/cpu/geometry/tracking_surface.cpp
  tests/unit_tests/cpu/navigation/navigator.cpp
  tests/unit_tests/cpu/propagator/rk_stepper.cpp
  tests/unit_tests/io/io_json_detector_writer.cpp
Labels: enhancement, refactor, priority: medium

#860 fix: Build SYCL tests on same machine as the test are run on and reactivate tests
  .gitlab-ci.yml
Labels: bug, priority: medium

#859 ref: Reactivate clang-format artifacts in CI
  .github/workflows/checks.yml
Labels: refactor, priority: low

#863 Ref: decouple stepper and navigator
  core/include/detray/navigation/detail/ray.hpp
  core/include/detray/navigation/navigator.hpp
  core/include/detray/navigation/policies.hpp
  core/include/detray/propagator/actors/aborters.hpp
  core/include/detray/propagator/base_stepper.hpp
  core/include/detray/propagator/line_stepper.hpp
  core/include/detray/propagator/propagator.hpp
  core/include/detray/propagator/rk_stepper.hpp
  core/include/detray/propagator/rk_stepper.ipp
  tests/include/detray/test/utils/inspectors.hpp
  tests/include/detray/test/utils/simulation/random_scatterer.hpp
  tests/include/detray/test/validation/step_tracer.hpp
  tests/integration_tests/cpu/propagator/jacobian_validation.cpp
  tests/integration_tests/cpu/propagator/propagator.cpp
  tests/unit_tests/cpu/detectors/telescope_detector.cpp
  tests/unit_tests/cpu/navigation/navigator.cpp
  tests/unit_tests/cpu/propagator/line_stepper.cpp
  tests/unit_tests/cpu/propagator/rk_stepper.cpp
  tests/unit_tests/device/cuda/navigator_cuda.cpp
  tests/unit_tests/device/cuda/navigator_cuda_kernel.cu
  tests/unit_tests/device/cuda/navigator_cuda_kernel.hpp
Labels: refactor, priority: medium

#850 Split propagate function into client components
  core/include/detray/propagator/propagator.hpp
Labels: refactor, priority: medium

#864 Ref: stepper state encapsulation
  core/include/detray/navigation/policies.hpp
  core/include/detray/propagator/actors/aborters.hpp
  core/include/detray/propagator/actors/parameter_resetter.hpp
  core/include/detray/propagator/actors/parameter_transporter.hpp
  core/include/detray/propagator/actors/pointwise_material_interactor.hpp
  core/include/detray/propagator/base_stepper.hpp
  core/include/detray/propagator/line_stepper.hpp
  core/include/detray/propagator/propagator.hpp
  core/include/detray/propagator/rk_stepper.hpp
  core/include/detray/propagator/rk_stepper.ipp
  tests/include/detray/test/utils/inspectors.hpp
  tests/include/detray/test/utils/simulation/random_scatterer.hpp
  tests/include/detray/test/validation/material_validation_utils.hpp
  tests/integration_tests/cpu/material/material_interaction.cpp
  tests/integration_tests/cpu/propagator/jacobian_validation.cpp
  tests/integration_tests/cpu/propagator/propagator.cpp
  tests/unit_tests/cpu/detectors/telescope_detector.cpp
  tests/unit_tests/cpu/propagator/covariance_transport.cpp
  tests/unit_tests/cpu/propagator/rk_stepper.cpp
Labels: refactor, priority: medium

#869 Project Export Fix, main branch (2024.10.24.)
  cmake/detray-config.cmake.in
Labels: bug, priority: high

#867 GCC 12 Build Fix, main branch (2024.10.22.)
  core/include/detray/core/detail/container_buffers.hpp
Labels: bug

#872 Add more `detray::tuple` features
  core/include/detray/utils/tuple.hpp
Labels: enhancement

#856 ref: Update the propagation config structs and improve navigation recovery due to extreme portal overstepping
  core/include/detray/navigation/navigation_config.hpp
  core/include/detray/navigation/navigator.hpp
  core/include/detray/propagator/line_stepper.hpp
  core/include/detray/propagator/propagator.hpp
  tests/include/detray/test/utils/inspectors.hpp
  tests/integration_tests/cpu/detectors/telescope_detector_navigation.cpp
  tests/integration_tests/cpu/material/material_interaction.cpp
  tests/integration_tests/cpu/propagator/guided_navigator.cpp
  tests/integration_tests/cpu/propagator/propagator.cpp
  tests/integration_tests/device/cuda/propagator_cuda.cpp
  tests/integration_tests/device/cuda/telescope_navigation_validation.cpp
  tests/unit_tests/cpu/navigation/navigator.cpp
  tests/unit_tests/cpu/propagator/covariance_transport.cpp
  tests/unit_tests/cpu/propagator/line_stepper.cpp
  tests/unit_tests/device/cuda/navigator_cuda.cpp
  tests/unit_tests/device/cuda/navigator_cuda_kernel.cu
  tests/unit_tests/device/cuda/navigator_cuda_kernel.hpp
  tutorials/src/cpu/propagation/navigation_inspection.cpp
Labels: bug, enhancement, refactor, priority: medium

#868 ref: Reduce size of navigation state
  core/include/detray/core/detector_metadata.hpp
  core/include/detray/geometry/detail/surface_descriptor.hpp
  core/include/detray/navigation/intersection/helix_cylinder_intersector.hpp
  core/include/detray/navigation/intersection/helix_intersector.hpp
  core/include/detray/navigation/intersection/helix_line_intersector.hpp
  core/include/detray/navigation/intersection/helix_plane_intersector.hpp
  core/include/detray/navigation/intersection/intersection.hpp
  core/include/detray/navigation/intersection/ray_concentric_cylinder_intersector.hpp
  core/include/detray/navigation/intersection/ray_cylinder_intersector.hpp
  core/include/detray/navigation/intersection/ray_cylinder_portal_intersector.hpp
  core/include/detray/navigation/intersection/ray_intersector.hpp
  core/include/detray/navigation/intersection/ray_line_intersector.hpp
  core/include/detray/navigation/intersection/ray_plane_intersector.hpp
  core/include/detray/navigation/intersection/soa/ray_cylinder_intersector.hpp
  core/include/detray/navigation/intersection/soa/ray_cylinder_portal_intersector.hpp
  core/include/detray/navigation/intersection/soa/ray_line_intersector.hpp
  core/include/detray/navigation/intersection/soa/ray_plane_intersector.hpp
  core/include/detray/navigation/intersection_kernel.hpp
  core/include/detray/navigation/intersector.hpp
  core/include/detray/navigation/navigation_config.hpp
  core/include/detray/navigation/navigator.hpp
  core/include/detray/propagator/propagator.hpp
  detectors/include/detray/detectors/itk_metadata.hpp
  detectors/include/detray/detectors/telescope_metadata.hpp
  detectors/include/detray/detectors/toy_metadata.hpp
  io/include/detray/io/csv/intersection2D.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/grid.hpp
  tests/include/detray/test/device/cuda/navigation_validation.cu
  tests/include/detray/test/utils/inspectors.hpp
  tests/include/detray/test/validation/detector_scanner.hpp
  tests/include/detray/test/validation/navigation_validation_utils.hpp
  tests/integration_tests/cpu/propagator/covariance_transport.cpp
  tests/unit_tests/cpu/detectors/telescope_detector.cpp
  tests/unit_tests/cpu/geometry/tracking_surface.cpp
  tests/unit_tests/cpu/material/materials.cpp
  tests/unit_tests/cpu/navigation/intersection/cylinder_intersector.cpp
  tests/unit_tests/cpu/navigation/intersection/helix_intersector.cpp
  tests/unit_tests/cpu/navigation/intersection/intersection2D.cpp
  tests/unit_tests/cpu/navigation/intersection/intersection_kernel.cpp
  tests/unit_tests/cpu/navigation/intersection/line_intersector.cpp
  tests/unit_tests/cpu/navigation/intersection/plane_intersector.cpp
  tests/unit_tests/cpu/navigation/navigator.cpp
  tests/unit_tests/cpu/propagator/covariance_transport.cpp
  tests/unit_tests/device/cuda/navigator_cuda.cpp
  tests/unit_tests/device/cuda/navigator_cuda_kernel.cu
  tutorials/include/detray/tutorial/detector_metadata.hpp
  tutorials/src/cpu/propagation/navigation_inspection.cpp
Labels: refactor, priority: medium

#874 Update CUDA version in CI to 12.6
  .github/workflows/builds.yml
Labels: bug, priority: high

#858 fix: Navigation assertions in validation tools
  io/include/detray/io/csv/track_parameters.hpp
  tests/include/detray/test/validation/step_tracer.hpp
Labels: bug, priority: medium
