Repository acts-project/detray, pull requests merged in 2024-12, with the labels that each got.

#885 ref: More realistic toy detector benchmarks
  tests/benchmarks/cpu/benchmark_propagator.cpp
  tests/benchmarks/cuda/benchmark_propagator_cuda.cpp
Labels: refactor, priority: low

#897 Enable line information in RelWithDebInfo
  cmake/detray-compiler-options-cuda.cmake
Labels: priority: low, build

#900 Explicitly disable git pager in pre-commit
  .pre-commit-config.yaml
Labels: bug, priority: low

#899 Simplify random access iterator advancement
  core/include/detray/utils/ranges/detail/iterator_functions.hpp
Labels: priority: low, optimization

#903 Remove the Navigation Direction Sign for Process Noise
  core/include/detray/propagator/actors/pointwise_material_interactor.hpp
  tests/integration_tests/cpu/material/material_interaction.cpp
  tests/integration_tests/cpu/propagator/backward_propagation.cpp
  tests/unit_tests/cpu/simulation/scattering.cpp
Labels: bug, priority: high

#906 Use approximate equality checks for 3D point tests
  tests/include/detray/test/common/assert.hpp
  tests/unit_tests/device/cuda/sf_finders_grid_cuda.cpp
Labels: bug, priority: medium

#898 Reenable FMA in CUDA builds
  cmake/detray-compiler-options-cuda.cmake
Labels: priority: medium, optimization, build
