Repository acts-project/detray, pull requests merged in 2024-04, with the labels that each got.

#715 CMake Updates, main branch (2024.04.12.)
  .github/workflows/builds.yml
  .gitignore
  .gitlab-ci.yml
  CMakeLists.txt
  CMakePresets.json
  cmake/detray-compiler-options-cpp.cmake
  cmake/detray-compiler-options-cuda.cmake
  cmake/detray-compiler-options-sycl.cmake
Labels: enhancement

#724 ref:Some additional checks during detector building
  core/include/detray/builders/detector_builder.hpp
  io/include/detray/io/common/detail/grid_reader.hpp
  io/include/detray/io/common/homogeneous_material_reader.hpp
  io/include/detray/io/common/material_map_reader.hpp
Labels: refactor, priority: low

#726 feat: dump truth intersections to file
  CMakeLists.txt
  cmake/detray-config.cmake.in
  extern/dfelibs/CMakeLists.txt
  extern/dfelibs/README.md
  io/CMakeLists.txt
  io/include/detray/io/common/detail/basic_converter.hpp
  io/include/detray/io/common/homogeneous_material_reader.hpp
  io/include/detray/io/common/homogeneous_material_writer.hpp
  io/include/detray/io/covfie/read_bfield.hpp
  io/include/detray/io/csv/intersection2D.hpp
  io/include/detray/io/csv/track_parameters.hpp
  io/include/detray/io/frontend/detail/detector_components_reader.hpp
  io/include/detray/io/frontend/detail/detector_components_writer.hpp
  io/include/detray/io/frontend/detail/io_metadata.hpp
  io/include/detray/io/frontend/detail/type_traits.hpp
  io/include/detray/io/frontend/detector_reader.hpp
  io/include/detray/io/frontend/detector_writer.hpp
  io/include/detray/io/frontend/implementation/json_readers.hpp
  io/include/detray/io/frontend/implementation/json_writers.hpp
  io/include/detray/io/frontend/utils/create_path.hpp
  io/include/detray/io/json/json_reader.hpp
  io/include/detray/io/json/json_writer.hpp
  io/include/detray/io/utils/create_path.hpp
  io/include/detray/io/utils/file_handle.hpp
  plugins/svgtools/include/detray/plugins/svgtools/writer.hpp
  tests/CMakeLists.txt
  tests/include/detray/test/detector_helix_scan.hpp
  tests/include/detray/test/detector_ray_scan.hpp
  tests/include/detray/test/helix_navigation.hpp
  tests/include/detray/test/straight_line_navigation.hpp
  tests/include/detray/test/utils/detector_scanner.hpp
  tests/include/detray/test/utils/navigation_check_helper.hpp
  tests/include/detray/test/utils/svg_display.hpp
  tests/integration_tests/cpu/detectors/telescope_detector_navigation.cpp
  tests/tools/CMakeLists.txt
  tests/tools/include/detray/validation/detector_material_scan.hpp
  tests/tools/src/detector_display.cpp
  tests/tools/src/detector_validation.cpp
  tests/unit_tests/cpu/propagator/rk_stepper.cpp
  tutorials/CMakeLists.txt
  utils/CMakeLists.txt
  utils/include/detray/detectors/create_toy_geometry.hpp
Labels: enhancement, priority: high
