Repository acts-project/detray, pull requests merged in 2024-06, with the labels that each got.

#747 ref: Count the number of missed surfaces in navigation validation
  tests/include/detray/test/common/utils/detector_scanner.hpp
  tests/include/detray/test/common/utils/navigation_validation_utils.hpp
  tests/include/detray/test/common/utils/svg_display.hpp
  tests/include/detray/test/cpu/detector_scan.hpp
  tests/include/detray/test/cpu/navigation_validation.hpp
  tests/include/detray/test/device/cuda/navigation_validation.hpp
  tests/validation/python/impl/__init__.py
  tests/validation/python/impl/plot_navigation_validation.py
  tests/validation/python/impl/plot_ray_scan.py
  tests/validation/python/impl/plot_track_positions.py
  tests/validation/python/navigation_validation.py
  tests/validation/python/plotting/pyplot_factory.py
Labels: enhancement, refactor, priority: high

#750 ref: Estimate phi tolerance from chord
  core/include/detray/geometry/detail/shape_utils.hpp
  core/include/detray/geometry/shapes/annulus2D.hpp
  core/include/detray/geometry/shapes/cylinder3D.hpp
  tests/unit_tests/cpu/geometry/masks/annulus2D.cpp
Labels: refactor, priority: medium

#751 ref: Add material maps to all portals in toy detector and harmonize with material scan
  tests/include/detray/test/common/utils/material_validation_utils.hpp
  tests/include/detray/test/cpu/material_scan.hpp
  tests/include/detray/test/cpu/material_validation.hpp
  tests/include/detray/test/cpu/toy_detector_test.hpp
  tests/integration_tests/cpu/detectors/toy_detector_navigation.cpp
  tests/tools/src/cpu/generate_toy_detector.cpp
  tests/validation/python/impl/plot_material_scan.py
  tests/validation/python/material_validation.py
  tests/validation/python/navigation_validation.py
  tests/validation/python/options/__init__.py
  tests/validation/python/options/track_generator_options.py
  utils/include/detray/detectors/build_toy_detector.hpp
Labels: bug, refactor, priority: high

#749 feat: Randomize charge in track generators and plot track parameter distributions
  core/include/detray/navigation/detail/helix.hpp
  core/include/detray/navigation/detail/ray.hpp
  io/include/detray/io/frontend/detector_writer_config.hpp
  tests/include/detray/test/common/utils/detector_scanner.hpp
  tests/include/detray/test/cpu/detector_scan.hpp
  tests/integration_tests/cpu/propagator/jacobian_validation.cpp
  tests/tools/include/detray/options/detector_io_options.hpp
  tests/tools/include/detray/options/track_generator_options.hpp
  tests/unit_tests/cpu/simulation/track_generators.cpp
  tests/validation/python/impl/__init__.py
  tests/validation/python/impl/plot_navigation_validation.py
  tests/validation/python/impl/plot_track_params.py
  tests/validation/python/navigation_validation.py
  tests/validation/python/options/track_generator_options.py
  tests/validation/python/plotting/pyplot_factory.py
  tutorials/src/cpu/detector/detector_ray_scan.cpp
  utils/include/detray/simulation/event_generator/random_numbers.hpp
  utils/include/detray/simulation/event_generator/random_track_generator.hpp
  utils/include/detray/simulation/event_generator/random_track_generator_config.hpp
  utils/include/detray/simulation/event_generator/uniform_track_generator.hpp
  utils/include/detray/simulation/event_generator/uniform_track_generator_config.hpp
Labels: enhancement, priority: medium

#748 feat: check distance to surface edge in navigation validation
  core/include/detray/builders/detail/portal_accessor.hpp
  core/include/detray/builders/grid_factory.hpp
  core/include/detray/builders/material_map_generator.hpp
  core/include/detray/geometry/detail/surface_kernels.hpp
  core/include/detray/geometry/mask.hpp
  core/include/detray/geometry/shapes/annulus2D.hpp
  core/include/detray/geometry/shapes/concentric_cylinder2D.hpp
  core/include/detray/geometry/shapes/cuboid3D.hpp
  core/include/detray/geometry/shapes/cylinder2D.hpp
  core/include/detray/geometry/shapes/cylinder3D.hpp
  core/include/detray/geometry/shapes/line.hpp
  core/include/detray/geometry/shapes/rectangle2D.hpp
  core/include/detray/geometry/shapes/ring2D.hpp
  core/include/detray/geometry/shapes/single3D.hpp
  core/include/detray/geometry/shapes/trapezoid2D.hpp
  core/include/detray/geometry/shapes/unbounded.hpp
  core/include/detray/geometry/shapes/unmasked.hpp
  core/include/detray/geometry/surface.hpp
  io/include/detray/io/common/geometry_reader.hpp
  io/include/detray/io/csv/intersection2D.hpp
  io/include/detray/io/csv/track_parameters.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/surface.hpp
  tests/include/detray/test/common/utils/navigation_validation_utils.hpp
  tests/include/detray/test/cpu/detector_scan.hpp
  tests/include/detray/test/cpu/navigation_validation.hpp
  tests/include/detray/test/device/cuda/navigation_validation.hpp
  tests/unit_tests/cpu/geometry/masks/annulus2D.cpp
  tests/unit_tests/cpu/geometry/masks/cylinder.cpp
  tests/unit_tests/svgtools/masks.cpp
  tests/validation/python/impl/__init__.py
  tests/validation/python/impl/plot_navigation_validation.py
  tests/validation/python/navigation_validation.py
  tutorials/include/detray/tutorial/my_square2D.hpp
Labels: bug, enhancement, refactor, priority: high

#753 feat: allow to read material map boundaries
  core/include/detray/builders/grid_factory.hpp
  core/include/detray/builders/material_map_builder.hpp
  core/include/detray/builders/material_map_factory.hpp
  io/include/detray/io/common/material_map_reader.hpp
  tests/integration_tests/cpu/builders/material_map_builder.cpp
  tests/unit_tests/cpu/builders/material_map_builder.cpp
Labels: enhancement, priority: high

#755 Fix non-conformant use of iterator type aliases
  tests/include/detray/test/common/utils/detector_scan_utils.hpp
Labels: bug

#756 Migrate static strings to `std::string_view`
  core/include/detray/builders/surface_factory.hpp
  core/include/detray/geometry/mask.hpp
  core/include/detray/geometry/shapes/annulus2D.hpp
  core/include/detray/geometry/shapes/concentric_cylinder2D.hpp
  core/include/detray/geometry/shapes/cuboid3D.hpp
  core/include/detray/geometry/shapes/cylinder2D.hpp
  core/include/detray/geometry/shapes/cylinder3D.hpp
  core/include/detray/geometry/shapes/line.hpp
  core/include/detray/geometry/shapes/rectangle2D.hpp
  core/include/detray/geometry/shapes/ring2D.hpp
  core/include/detray/geometry/shapes/single3D.hpp
  core/include/detray/geometry/shapes/trapezoid2D.hpp
  core/include/detray/geometry/shapes/unbounded.hpp
  core/include/detray/geometry/shapes/unmasked.hpp
  core/include/detray/utils/string_view_concat.hpp
  io/include/detray/io/common/geometry_reader.hpp
  io/include/detray/io/common/geometry_writer.hpp
  io/include/detray/io/common/homogeneous_material_reader.hpp
  io/include/detray/io/common/homogeneous_material_writer.hpp
  io/include/detray/io/common/material_map_reader.hpp
  io/include/detray/io/common/material_map_writer.hpp
  io/include/detray/io/common/surface_grid_reader.hpp
  io/include/detray/io/common/surface_grid_writer.hpp
  io/include/detray/io/frontend/detail/io_metadata.hpp
  io/include/detray/io/json/json_writer.hpp
  tests/include/detray/test/cpu/material_validation.hpp
  tests/include/detray/test/device/cuda/material_validation.hpp
  tests/unit_tests/cpu/geometry/masks/unbounded.cpp
  tutorials/include/detray/tutorial/my_square2D.hpp
Labels: refactor

#754 ref: Make Newton convergence more robust
  core/include/detray/navigation/intersection/helix_cylinder_intersector.hpp
  core/include/detray/navigation/intersection/helix_line_intersector.hpp
  core/include/detray/navigation/intersection/helix_plane_intersector.hpp
  core/include/detray/navigation/navigation_config.hpp
  core/include/detray/utils/root_finding.hpp
  tests/include/detray/test/common/utils/navigation_validation_utils.hpp
  tests/integration_tests/cpu/detectors/toy_detector_navigation.cpp
  tests/integration_tests/cpu/detectors/wire_chamber_navigation.cpp
  tests/integration_tests/cpu/propagator/covariance_transport.cpp
  tests/integration_tests/cpu/propagator/jacobian_validation.cpp
  tests/unit_tests/cpu/navigation/navigator.cpp
  tests/validation/python/impl/plot_track_params.py
  tests/validation/python/navigation_validation.py
  tests/validation/python/options/propagation_options.py
  tests/validation/python/plotting/pyplot_factory.py
Labels: bug, refactor, priority: high

#759 ref: Update to new actsvg version and fix some bugs
  extern/actsvg/CMakeLists.txt
  plugins/svgtools/include/detray/plugins/svgtools/utils/surface_kernels.hpp
  tests/tools/src/cpu/generate_telescope_detector.cpp
Labels: bug, enhancement, refactor, priority: high

#760 ref: add momentum information to file names and finalize plots
  plugins/svgtools/include/detray/plugins/svgtools/conversion/intersection.hpp
  plugins/svgtools/include/detray/plugins/svgtools/illustrator.hpp
  tests/include/detray/test/common/detector_scan_config.hpp
  tests/include/detray/test/cpu/detector_scan.hpp
  tests/include/detray/test/cpu/navigation_validation.hpp
  tests/include/detray/test/device/cuda/navigation_validation.hpp
  tests/tools/include/detray/options/propagation_options.hpp
  tests/tools/src/cpu/detector_validation.cpp
  tests/tools/src/cpu/generate_toy_detector.cpp
  tests/tools/src/cuda/detector_validation_cuda.cpp
  tests/validation/python/impl/plot_navigation_validation.py
  tests/validation/python/impl/plot_ray_scan.py
  tests/validation/python/impl/plot_track_params.py
  tests/validation/python/navigation_validation.py
  tests/validation/python/plotting/pyplot_factory.py
Labels: bug, refactor, priority: high

#762 ref: Use relative error in material comparison and improve material plots
  tests/include/detray/test/common/material_validation_config.hpp
  tests/include/detray/test/cpu/material_validation.hpp
  tests/integration_tests/cpu/detectors/toy_detector_navigation.cpp
  tests/integration_tests/cpu/detectors/wire_chamber_navigation.cpp
  tests/integration_tests/device/cuda/toy_detector_navigation_validation.cpp
  tests/integration_tests/device/cuda/wire_chamber_navigation_validation.cpp
  tests/tools/src/cpu/material_validation.cpp
  tests/tools/src/cuda/material_validation_cuda.cpp
  tests/validation/python/impl/plot_material_scan.py
  tests/validation/python/impl/plot_navigation_validation.py
  tests/validation/python/impl/plot_track_params.py
  tests/validation/python/material_validation.py
  tests/validation/python/navigation_validation.py
  tests/validation/python/plotting/pyplot_factory.py
Labels: refactor, priority: high
