Repository acts-project/detray, pull requests merged in 2024-01, with the labels that each got.

#618 bug: Add compiler sanitizer option and fix errors
  CMakeLists.txt
  cmake/detray-functions.cmake
  core/include/detray/grids/axis.hpp
  core/include/detray/intersection/bounding_box/cuboid_intersector.hpp
  core/include/detray/materials/detail/relativistic_quantities.hpp
  core/include/detray/propagator/actors/aborters.hpp
  core/include/detray/propagator/rk_stepper.ipp
  core/include/detray/surface_finders/grid/grid_collection.hpp
  core/include/detray/tools/bounding_volume.hpp
  core/include/detray/tools/cuboid_portal_generator.hpp
  core/include/detray/tools/detector_builder.hpp
  core/include/detray/tools/material_factory.hpp
  core/include/detray/tools/surface_factory.hpp
  core/include/detray/tools/volume_builder.hpp
  core/include/detray/utils/inspectors.hpp
  core/include/detray/utils/ranges/pick.hpp
  tests/common/include/tests/common/tools/ray_scan_utils.hpp
  tests/unit_tests/core/utils_ranges.cpp
  tests/unit_tests/cpu/tools_helix_intersectors.cpp
  tests/unit_tests/cpu/tools_helix_trajectory.cpp
  tests/unit_tests/cpu/tools_stepper.cpp
  utils/include/detray/detectors/create_toy_geometry.hpp
  utils/include/detray/detectors/create_wire_chamber.hpp
  utils/include/detray/simulation/event_generator/random_track_generator.hpp
Labels: bug, enhancement, priority: high

#623 Normalize direction of helix
  core/include/detray/intersection/detail/trajectories.hpp
Labels: bug

#620 ref: grid cleanup and decoupling the bin storage
  core/include/detray/coordinates/cartesian2.hpp
  core/include/detray/coordinates/cartesian3.hpp
  core/include/detray/coordinates/cylindrical2.hpp
  core/include/detray/coordinates/cylindrical3.hpp
  core/include/detray/coordinates/line2.hpp
  core/include/detray/coordinates/polar2.hpp
  core/include/detray/core/detail/multi_store.hpp
  core/include/detray/core/detector.hpp
  core/include/detray/core/detector_metadata.hpp
  core/include/detray/materials/material_map.hpp
  core/include/detray/propagator/navigator.hpp
  core/include/detray/propagator/propagator.hpp
  core/include/detray/propagator/rk_stepper.ipp
  core/include/detray/surface_finders/accelerator_grid.hpp
  core/include/detray/surface_finders/grid/axis.hpp
  core/include/detray/surface_finders/grid/detail/axis_binning.hpp
  core/include/detray/surface_finders/grid/detail/axis_helpers.hpp
  core/include/detray/surface_finders/grid/detail/bin_storage.hpp
  core/include/detray/surface_finders/grid/detail/bin_view.hpp
  core/include/detray/surface_finders/grid/detail/grid_bins.hpp
  core/include/detray/surface_finders/grid/detail/grid_helpers.hpp
  core/include/detray/surface_finders/grid/detail/populator_impl.hpp
  core/include/detray/surface_finders/grid/detail/simple_serializer.hpp
  core/include/detray/surface_finders/grid/grid.hpp
  core/include/detray/surface_finders/grid/grid_collection.hpp
  core/include/detray/surface_finders/grid/populator.hpp
  core/include/detray/surface_finders/grid/populators.hpp
  core/include/detray/surface_finders/grid/serializers.hpp
  core/include/detray/tools/bin_association.hpp
  core/include/detray/tools/bin_fillers.hpp
  core/include/detray/tools/grid_builder.hpp
  core/include/detray/tools/grid_factory.hpp
  core/include/detray/utils/ranges/join.hpp
  core/include/detray/utils/ranges/pointer.hpp
  core/include/detray/utils/ranges/ranges.hpp
  core/include/detray/utils/ranges/single.hpp
  core/include/detray/utils/ranges/subrange.hpp
  core/include/detray/utils/type_list.hpp
  core/include/detray/utils/type_registry.hpp
  io/include/detray/io/common/detail/grid_writer.hpp
  io/include/detray/io/common/detector_reader.hpp
  io/include/detray/io/common/grid_reader.hpp
  tests/unit_tests/core/utils_type_list.cpp
  tests/unit_tests/cpu/grid_axis.cpp
  tests/unit_tests/cpu/grid_grid.cpp
  tests/unit_tests/cpu/grid_grid_builder.cpp
  tests/unit_tests/cpu/grid_grid_collection.cpp
  tests/unit_tests/cpu/grid_populator.cpp
  tests/unit_tests/cpu/grid_serializer.cpp
  tests/unit_tests/cpu/material_maps.cpp
  tests/unit_tests/device/cuda/sf_finders_grid_cuda.cpp
  tests/unit_tests/device/cuda/sf_finders_grid_cuda_kernel.cu
  tests/unit_tests/device/cuda/sf_finders_grid_cuda_kernel.hpp
  tests/validation/include/detray/validation/detector_material_scan.hpp
  tutorials/include/detray/tutorial/detector_metadata.hpp
  utils/include/detray/detectors/detector_helper.hpp
  utils/include/detray/detectors/itk_metadata.hpp
  utils/include/detray/detectors/toy_metadata.hpp
Labels: refactor, priority: high

#627 Fix qoverp calculation in the RK stepper
  core/include/detray/propagator/rk_stepper.hpp
  core/include/detray/propagator/rk_stepper.ipp
Labels: bug

#632 Remove the factor of 2 in compraing error tolerance
  core/include/detray/propagator/rk_stepper.ipp
Labels: priority: high

#637 ref: remove radius from 2D cylinder grid
  core/include/detray/coordinates/cylindrical2.hpp
  core/include/detray/tools/grid_factory.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/grid.hpp
  tests/unit_tests/cpu/material_maps.cpp
Labels: bug, priority: medium

#642 feat: grid benchmarks
  core/include/detray/grids/grid2.hpp
  core/include/detray/grids/populator.hpp
  tests/benchmarks/cpu/CMakeLists.txt
  tests/benchmarks/cpu/grid.cpp
  tests/benchmarks/cpu/grid2.cpp
  tests/benchmarks/cpu/grids.cpp
  tests/benchmarks/cpu/intersect_surfaces.cpp
Labels: enhancement, priority: low
