Repository acts-project/detray, pull requests merged in 2025-06, with the labels that each got.

#998 fix: Material maps display and scale toy material maps
  core/include/detray/builders/material_map_generator.hpp
  plugins/svgtools/include/detray/plugins/svgtools/conversion/surface_material.hpp
  plugins/svgtools/include/detray/plugins/svgtools/styling/styling.hpp
  tests/include/detray/test/common/build_toy_detector.hpp
  tests/include/detray/test/cpu/material_validation.hpp
  tests/include/detray/test/cpu/toy_detector_test.hpp
  tests/integration_tests/cpu/detectors/toy_detector_navigation.cpp
Labels: bug

#997 Reduce thread divergence in covariance transport
  core/include/detray/geometry/detail/tracking_surface_kernels.hpp
  core/include/detray/geometry/tracking_surface.hpp
  core/include/detray/propagator/actors/parameter_transporter.hpp
  core/include/detray/propagator/detail/jacobian_engine.hpp
  core/include/detray/utils/curvilinear_frame.hpp
  tests/integration_tests/cpu/propagator/covariance_transport.cpp
  tests/unit_tests/cpu/propagator/jacobian_cartesian.cpp
  tests/unit_tests/cpu/propagator/jacobian_cylindrical.cpp
  tests/unit_tests/cpu/propagator/jacobian_line.cpp
  tests/unit_tests/cpu/propagator/jacobian_polar.cpp
Labels: refactor, performance

#1005 fix: index range size
  core/include/detray/core/detail/indexing.hpp
  core/include/detray/utils/bit_encoder.hpp
  tests/include/detray/test/cpu/toy_detector_test.hpp
  tests/unit_tests/cpu/core/indexing.cpp
Labels: bug, priority: high

#1004 feat: printable detector
  core/include/detray/core/detector.hpp
  core/include/detray/geometry/tracking_volume.hpp
  core/include/detray/navigation/accelerators/brute_force_finder.hpp
  core/include/detray/utils/consistency_checker.hpp
  core/include/detray/utils/grid/detail/axis.hpp
  core/include/detray/utils/grid/grid.hpp
  core/include/detray/utils/print_detector.hpp
  io/include/detray/io/frontend/detector_reader.hpp
  plugins/svgtools/include/detray/plugins/svgtools/illustrator.hpp
Labels: enhancement

#1011 feat: Add number of physical cores to scaling plots
  tests/tools/python/impl/plot_benchmark_results.py
  tests/tools/python/impl/plot_detector_scan.py
  tests/tools/python/plotting/pyplot_factory.py
  tests/tools/python/propagation_benchmarks.py
  tests/tools/src/cpu/propagation_scaling.cpp
Labels: enhancement, refactor

#1012 feat: Configurable axes in detector display
  plugins/svgtools/include/detray/plugins/svgtools/illustrator.hpp
  plugins/svgtools/include/detray/plugins/svgtools/meta/proto/eta_lines.hpp
  tests/tools/src/cpu/detector_display.cpp
Labels: enhancement
