Repository acts-project/detray, pull requests merged in 2025-08, with the labels that each got.

#1042 fix: Switch on all benchmark build variations in the CI
  .github/workflows/builds.yml
Labels: bug, build

#1043 fix: CUDA integration test linking and make cmake more verbose
  plugins/algebra/CMakeLists.txt
  tests/CMakeLists.txt
  tests/benchmarks/include/detray/benchmarks/cpu/CMakeLists.txt
  tests/benchmarks/include/detray/benchmarks/device/cuda/CMakeLists.txt
  tests/include/detray/test/cpu/CMakeLists.txt
  tests/include/detray/test/device/CMakeLists.txt
  tests/include/detray/test/device/cuda/CMakeLists.txt
  tests/integration_tests/device/cuda/CMakeLists.txt
  tests/tools/CMakeLists.txt
  tests/tools/src/cuda/CMakeLists.txt
Labels: build, cleanup

#1056 feat: add HIP backends to python benchmark script and fix a few warnings
  core/include/detray/definitions/detail/hip_definitions.hpp
  tests/benchmarks/include/detray/benchmarks/device/hip/propagation_benchmark.hip
  tests/tools/python/propagation_benchmarks.py
Labels: bug, enhancement, cleanup

#1055 fix: navigation validation utils
  tests/include/detray/test/validation/navigation_validation_utils.hpp
Labels: bug, enhancement, priority: high

#1058 Add Sympy generator for RK stepper Jacobian
  codegen/detray-sympy/gen_update_rk_transport_jacobian_impl.py
  core/include/detray/propagator/base_stepper.hpp
  core/include/detray/propagator/codegen/update_rk_transport_jacobian.hpp
  core/include/detray/propagator/rk_stepper.ipp
Labels: performance
