Repository acts-project/detray, pull requests merged in 2025-07, with the labels that each got.

#1015 feat: adjustable gradient box position
  tests/tools/src/cpu/detector_display.cpp
Labels: enhancement

#1017 Fix: data dir option for cuda material validation
  core/include/detray/utils/consistency_checker.hpp
  tests/include/detray/test/common/event_generator/uniform_track_generator_config.hpp
  tests/tools/src/cpu/detector_display.cpp
  tests/tools/src/cuda/material_validation_cuda.cpp
Labels: bug

#1006 Flatten propagation loop structure
  core/include/detray/navigation/navigator.hpp
  core/include/detray/propagator/propagator.hpp
Labels: refactor, performance

#1018 Update version number to v0.101.0
  CMakeLists.txt
Labels: build

#1019 ref: Remove verbose print
  tests/integration_tests/cpu/propagator/propagator.cpp
Labels: refactor
