Repository acts-project/detray, pull requests merged in 2025-03, with the labels that each got.

#940 fix: state tuple type and remove empty states
  core/include/detray/propagator/actor_chain.hpp
  core/include/detray/propagator/base_actor.hpp
  core/include/detray/propagator/propagator.hpp
  core/include/detray/utils/tuple_helpers.hpp
  tests/benchmarks/cpu/propagation.cpp
  tests/benchmarks/cuda/propagation.cpp
  tests/benchmarks/include/detray/benchmarks/cpu/propagation_benchmark.hpp
  tests/include/detray/test/device/cuda/material_validation.cu
  tests/include/detray/test/device/propagator_test.hpp
  tests/include/detray/test/utils/simulation/random_scatterer.hpp
  tests/include/detray/test/validation/material_validation_utils.hpp
  tests/integration_tests/cpu/material/material_interaction.cpp
  tests/integration_tests/cpu/propagator/backward_propagation.cpp
  tests/integration_tests/cpu/propagator/jacobian_validation.cpp
  tests/integration_tests/cpu/propagator/propagator.cpp
  tests/integration_tests/device/cuda/propagator_cuda_kernel.cu
  tests/integration_tests/device/sycl/propagator_kernel.sycl
  tests/tools/src/cpu/propagation_benchmark.cpp
  tests/tools/src/cpu/propagation_scaling.cpp
  tests/tools/src/cuda/propagation_benchmark_cuda.cpp
  tests/unit_tests/cpu/propagator/covariance_transport.cpp
  tutorials/src/device/cuda/propagation_kernel.cu
Labels: bug, enhancement, priority: low

#947 fix: a few compiler warnings
  core/include/detray/builders/detail/bin_association.hpp
  tests/include/detray/test/utils/detectors/build_toy_detector.hpp
Labels: bug, cleanup

#948 Implementing direct navigator
  core/include/detray/navigation/direct_navigator.hpp
  core/include/detray/navigation/intersection/ray_cylinder_intersector.hpp
  core/include/detray/navigation/intersection/ray_cylinder_portal_intersector.hpp
  core/include/detray/navigation/navigator.hpp
  core/include/detray/propagator/actors.hpp
  core/include/detray/propagator/actors/barcode_sequencer.hpp
  core/include/detray/propagator/propagator.hpp
  tests/integration_tests/cpu/material/material_interaction.cpp
  tests/integration_tests/cpu/propagator/backward_propagation.cpp
  tests/integration_tests/cpu/propagator/propagator.cpp
  tests/unit_tests/cpu/propagator/covariance_transport.cpp
Labels: bug, enhancement, priority: high

#943 Fix: Calculation of surface finding efficiency per type
  tests/include/detray/test/cpu/navigation_validation.hpp
  tests/include/detray/test/device/cuda/navigation_validation.hpp
  tests/include/detray/test/validation/navigation_validation_utils.hpp
  tests/include/detray/test/validation/svg_display.hpp
Labels: bug, enhancement, priority: high

#957 ref: Allow to construct helices from all b field types
  core/include/detray/navigation/intersection/helix_line_intersector.hpp
  core/include/detray/tracks/helix.hpp
  tests/include/detray/test/cpu/detector_scan.hpp
  tests/include/detray/test/cpu/navigation_validation.hpp
  tests/include/detray/test/device/cuda/navigation_validation.hpp
  tests/integration_tests/cpu/propagator/covariance_transport.cpp
  tests/integration_tests/cpu/propagator/jacobian_validation.cpp
  tests/integration_tests/cpu/propagator/propagator.cpp
  tests/tools/src/cpu/generate_telescope_detector.cpp
  tests/unit_tests/cpu/detectors/telescope_detector.cpp
  tests/unit_tests/cpu/navigation/intersection/helix_intersector.cpp
  tests/unit_tests/cpu/navigation/intersection/helix_trajectory.cpp
  tests/unit_tests/cpu/navigation/intersection/intersection_kernel.cpp
  tests/unit_tests/cpu/propagator/rk_stepper.cpp
  tests/unit_tests/cpu/simulation/detector_scanner.cpp
  tests/unit_tests/cpu/simulation/track_generators.cpp
  tests/unit_tests/svgtools/trajectories.cpp
  tests/unit_tests/svgtools/web.cpp
  tutorials/src/cpu/detector/build_predefined_detectors.cpp
Labels: refactor

#964 Remove full jacobian from stepper
  core/include/detray/propagator/actors/parameter_transporter.hpp
  core/include/detray/propagator/base_stepper.hpp
  tests/integration_tests/cpu/propagator/jacobian_validation.cpp
Labels: performance

#941 feat: actor concepts
  core/include/detray/propagator/actor_chain.hpp
  core/include/detray/propagator/actors.hpp
  core/include/detray/propagator/base_actor.hpp
  core/include/detray/propagator/composite_actor.hpp
  core/include/detray/propagator/concepts.hpp
  core/include/detray/propagator/detail/type_traits.hpp
  core/include/detray/propagator/propagator.hpp
  core/include/detray/utils/concepts.hpp
  core/include/detray/utils/tuple_helpers.hpp
  tests/integration_tests/cpu/material/material_interaction.cpp
  tests/integration_tests/cpu/propagator/propagator.cpp
  tests/unit_tests/cpu/propagator/actor_chain.cpp
  tests/unit_tests/cpu/propagator/covariance_transport.cpp
  tests/unit_tests/cpu/utils/tuple_helpers.cpp
Labels: enhancement, priority: low

#956 Prevent CMake flags from propagating to parent
  README.md
  cmake/detray-compiler-options-cpp.cmake
  cmake/detray-compiler-options-cuda.cmake
  cmake/detray-compiler-options-sycl.cmake
Labels: bug, build
