Repository acts-project/detray, pull requests merged in 2025-02, with the labels that each got.

#921 ref: CLI tools cmake config
  CMakeLists.txt
  tests/CMakeLists.txt
  tests/include/detray/test/device/cuda/material_validation.hpp
  tests/tools/CMakeLists.txt
  tests/tools/src/cpu/CMakeLists.txt
  tests/tools/src/cuda/CMakeLists.txt
Labels: refactor, priority: high

#911 Ref: Add concepts and restructure io directories
  core/include/detray/builders/surface_factory_interface.hpp
  core/include/detray/core/concepts.hpp
  core/include/detray/core/detail/type_traits.hpp
  io/CMakeLists.txt
  io/include/detray/io/backend/concepts.hpp
  io/include/detray/io/backend/detail/basic_converter.hpp
  io/include/detray/io/backend/detail/grid_reader.hpp
  io/include/detray/io/backend/detail/grid_writer.hpp
  io/include/detray/io/backend/detail/type_info.hpp
  io/include/detray/io/backend/geometry_reader.hpp
  io/include/detray/io/backend/geometry_writer.hpp
  io/include/detray/io/backend/homogeneous_material_reader.hpp
  io/include/detray/io/backend/homogeneous_material_writer.hpp
  io/include/detray/io/backend/material_map_reader.hpp
  io/include/detray/io/backend/material_map_writer.hpp
  io/include/detray/io/backend/surface_grid_reader.hpp
  io/include/detray/io/backend/surface_grid_writer.hpp
  io/include/detray/io/csv/track_parameters.hpp
  io/include/detray/io/frontend/detector_reader.hpp
  io/include/detray/io/frontend/detector_writer.hpp
  io/include/detray/io/frontend/impl/json_readers.hpp
  io/include/detray/io/frontend/impl/json_writers.hpp
  io/include/detray/io/json/detail/json_algebra_io.hpp
  io/include/detray/io/json/detail/json_common_io.hpp
  io/include/detray/io/json/detail/json_geometry_io.hpp
  io/include/detray/io/json/detail/json_grids_io.hpp
  io/include/detray/io/json/detail/json_material_io.hpp
  io/include/detray/io/json/json_converter.hpp
  io/include/detray/io/json/json_io.hpp
  io/include/detray/io/json/json_reader.hpp
  io/include/detray/io/json/json_writer.hpp
  io/include/detray/io/utils/io_metadata.hpp
  tests/integration_tests/io/io_json_detector_roundtrip.cpp
  tests/unit_tests/io/io_json_detector_writer.cpp
  tutorials/include/detray/tutorial/detector_metadata.hpp
Labels: refactor, priority: low

#928 fix: Type printing
  core/include/detray/utils/type_list.hpp
  tests/unit_tests/cpu/utils/type_list.cpp
Labels: bug, priority: high

#929 fix: type printing version 2
  core/include/detray/geometry/shapes/unbounded.hpp
  core/include/detray/utils/string_helpers.hpp
  core/include/detray/utils/string_view_concat.hpp
  core/include/detray/utils/type_list.hpp
Labels: bug, priority: high

#931 Add some assertions to the surface lookup
  core/include/detray/core/detail/surface_lookup.hpp
Labels: priority: low

#932 Add PDG particle 0 to model errors
  core/include/detray/definitions/pdg_particle.hpp
Labels: enhancement, priority: medium

#935 fix: Use explicit types in cartesian product dereferencing
  core/include/detray/utils/grid/detail/bin_storage.hpp
  core/include/detray/utils/grid/detail/bin_view.hpp
  core/include/detray/utils/ranges/cartesian_product.hpp
  core/include/detray/utils/ranges/enumerate.hpp
  core/include/detray/utils/ranges/iota.hpp
  core/include/detray/utils/ranges/pick.hpp
Labels: bug

#936 ref: New iterator type alias
  core/include/detray/navigation/volume_graph.hpp
  core/include/detray/utils/find_bound.hpp
  core/include/detray/utils/grid/detail/axis_binning.hpp
  core/include/detray/utils/grid/detail/bin_storage.hpp
  core/include/detray/utils/grid/detail/bin_view.hpp
  core/include/detray/utils/ranges/cartesian_product.hpp
  core/include/detray/utils/ranges/detail/iterator_functions.hpp
  core/include/detray/utils/ranges/enumerate.hpp
  core/include/detray/utils/ranges/join.hpp
  core/include/detray/utils/ranges/pick.hpp
  core/include/detray/utils/ranges/ranges.hpp
  core/include/detray/utils/ranges/static_join.hpp
  tests/include/detray/test/validation/detector_scan_utils.hpp
Labels: refactor, priority: low

#937 feat: Ranges pipe operator
  core/include/detray/utils/concepts.hpp
  core/include/detray/utils/ranges/cartesian_product.hpp
  core/include/detray/utils/ranges/enumerate.hpp
  core/include/detray/utils/ranges/iota.hpp
  core/include/detray/utils/ranges/join.hpp
  core/include/detray/utils/ranges/pick.hpp
  core/include/detray/utils/ranges/pointer.hpp
  core/include/detray/utils/ranges/ranges.hpp
  core/include/detray/utils/ranges/single.hpp
  core/include/detray/utils/ranges/static_join.hpp
  core/include/detray/utils/ranges/subrange.hpp
  tests/integration_tests/cpu/CMakeLists.txt
  tests/integration_tests/cpu/utils/ranges.cpp
  tests/unit_tests/cpu/utils/ranges.cpp
Labels: bug, enhancement, priority: low

#942 Fix: a few warnings about uninitialized values
  core/include/detray/builders/detail/bin_association.hpp
  tests/unit_tests/cpu/geometry/tracking_surface.cpp
  tests/unit_tests/cpu/navigation/intersection/intersection_kernel.cpp
Labels: cleanup

#945 Remove dependency on dfelibs
  CMakeLists.txt
  CMakePresets.json
  cmake/detray-config.cmake.in
  extern/dfelibs/CMakeLists.txt
  extern/dfelibs/README.md
  io/CMakeLists.txt
  io/include/detray/io/csv/dfe.hpp
  io/include/detray/io/csv/intersection2D.hpp
  io/include/detray/io/csv/track_parameters.hpp
  tests/CMakeLists.txt
  tests/benchmarks/CMakeLists.txt
  tutorials/CMakeLists.txt
Labels: build

#944 Change default overstep tolerance to -1 mm
  core/include/detray/navigation/navigation_config.hpp
  core/include/detray/navigation/navigator.hpp
Labels: bug
